/**
 * Midwest West Region
 * States: Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, South Dakota
 * 7 states, ~760 counties
 */

import type { StateData } from './types';

export const midwestWestStates: Record<string, StateData> = {
  // ===========================================================================
  // IOWA
  // ===========================================================================
  'iowa': {
    slug: 'iowa',
    name: 'Iowa',
    nameEs: 'Iowa',
    countyCount: 99,
    additionalContent: 'Iowa tiene una comunidad hispana en crecimiento, especialmente en Des Moines, las áreas empacadoras de carne, y las comunidades agrícolas. Los tribunales de familia en los 99 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Iowa?',
        answer: 'Sí. En los 99 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adair', city: 'Greenfield' },
      { name: 'Adams', city: 'Corning' },
      { name: 'Allamakee', city: 'Waukon' },
      { name: 'Appanoose', city: 'Centerville' },
      { name: 'Audubon', city: 'Audubon' },
      { name: 'Benton', city: 'Vinton' },
      { name: 'Black Hawk', city: 'Waterloo' },
      { name: 'Boone', city: 'Boone' },
      { name: 'Bremer', city: 'Waverly' },
      { name: 'Buchanan', city: 'Independence' },
      { name: 'Buena Vista', city: 'Storm Lake' },
      { name: 'Butler', city: 'Allison' },
      { name: 'Calhoun', city: 'Rockwell City' },
      { name: 'Carroll', city: 'Carroll' },
      { name: 'Cass', city: 'Atlantic' },
      { name: 'Cedar', city: 'Tipton' },
      { name: 'Cerro Gordo', city: 'Mason City' },
      { name: 'Cherokee', city: 'Cherokee' },
      { name: 'Chickasaw', city: 'New Hampton' },
      { name: 'Clarke', city: 'Osceola' },
      { name: 'Clay', city: 'Spencer' },
      { name: 'Clayton', city: 'Elkader' },
      { name: 'Clinton', city: 'Clinton' },
      { name: 'Crawford', city: 'Denison' },
      { name: 'Dallas', city: 'Adel' },
      { name: 'Davis', city: 'Bloomfield' },
      { name: 'Decatur', city: 'Leon' },
      { name: 'Delaware', city: 'Manchester' },
      { name: 'Des Moines', city: 'Burlington' },
      { name: 'Dickinson', city: 'Spirit Lake' },
      { name: 'Dubuque', city: 'Dubuque' },
      { name: 'Emmet', city: 'Estherville' },
      { name: 'Fayette', city: 'West Union' },
      { name: 'Floyd', city: 'Charles City' },
      { name: 'Franklin', city: 'Hampton' },
      { name: 'Fremont', city: 'Sidney' },
      { name: 'Greene', city: 'Jefferson' },
      { name: 'Grundy', city: 'Grundy Center' },
      { name: 'Guthrie', city: 'Guthrie Center' },
      { name: 'Hamilton', city: 'Webster City' },
      { name: 'Hancock', city: 'Garner' },
      { name: 'Hardin', city: 'Eldora' },
      { name: 'Harrison', city: 'Logan' },
      { name: 'Henry', city: 'Mount Pleasant' },
      { name: 'Howard', city: 'Cresco' },
      { name: 'Humboldt', city: 'Dakota City' },
      { name: 'Ida', city: 'Ida Grove' },
      { name: 'Iowa', city: 'Marengo' },
      { name: 'Jackson', city: 'Maquoketa' },
      { name: 'Jasper', city: 'Newton' },
      { name: 'Jefferson', city: 'Fairfield' },
      { name: 'Johnson', city: 'Iowa City' },
      { name: 'Jones', city: 'Anamosa' },
      { name: 'Keokuk', city: 'Sigourney' },
      { name: 'Kossuth', city: 'Algona' },
      { name: 'Lee', city: 'Fort Madison' },
      { name: 'Linn', city: 'Cedar Rapids' },
      { name: 'Louisa', city: 'Wapello' },
      { name: 'Lucas', city: 'Chariton' },
      { name: 'Lyon', city: 'Rock Rapids' },
      { name: 'Madison', city: 'Winterset' },
      { name: 'Mahaska', city: 'Oskaloosa' },
      { name: 'Marion', city: 'Knoxville' },
      { name: 'Marshall', city: 'Marshalltown' },
      { name: 'Mills', city: 'Glenwood' },
      { name: 'Mitchell', city: 'Osage' },
      { name: 'Monona', city: 'Onawa' },
      { name: 'Monroe', city: 'Albia' },
      { name: 'Montgomery', city: 'Red Oak' },
      { name: 'Muscatine', city: 'Muscatine' },
      { name: "O'Brien", city: 'Primghar' },
      { name: 'Osceola', city: 'Sibley' },
      { name: 'Page', city: 'Clarinda' },
      { name: 'Palo Alto', city: 'Emmetsburg' },
      { name: 'Plymouth', city: 'Le Mars' },
      { name: 'Pocahontas', city: 'Pocahontas' },
      { name: 'Polk', city: 'Des Moines' },
      { name: 'Pottawattamie', city: 'Council Bluffs' },
      { name: 'Poweshiek', city: 'Montezuma' },
      { name: 'Ringgold', city: 'Mount Ayr' },
      { name: 'Sac', city: 'Sac City' },
      { name: 'Scott', city: 'Davenport' },
      { name: 'Shelby', city: 'Harlan' },
      { name: 'Sioux', city: 'Orange City' },
      { name: 'Story', city: 'Nevada' },
      { name: 'Tama', city: 'Toledo' },
      { name: 'Taylor', city: 'Bedford' },
      { name: 'Union', city: 'Creston' },
      { name: 'Van Buren', city: 'Keosauqua' },
      { name: 'Wapello', city: 'Ottumwa' },
      { name: 'Warren', city: 'Indianola' },
      { name: 'Washington', city: 'Washington' },
      { name: 'Wayne', city: 'Corydon' },
      { name: 'Webster', city: 'Fort Dodge' },
      { name: 'Winnebago', city: 'Forest City' },
      { name: 'Winneshiek', city: 'Decorah' },
      { name: 'Woodbury', city: 'Sioux City' },
      { name: 'Worth', city: 'Northwood' },
      { name: 'Wright', city: 'Clarion' },
    ],
  },

  // ===========================================================================
  // KANSAS
  // ===========================================================================
  'kansas': {
    slug: 'kansas',
    name: 'Kansas',
    nameEs: 'Kansas',
    countyCount: 105,
    additionalContent: 'Kansas tiene una comunidad hispana significativa, especialmente en Garden City, Dodge City, Liberal, y las áreas empacadoras de carne del suroeste. Los tribunales de familia en los 105 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Kansas?',
        answer: 'Sí. En los 105 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Allen', city: 'Iola' },
      { name: 'Anderson', city: 'Garnett' },
      { name: 'Atchison', city: 'Atchison' },
      { name: 'Barber', city: 'Medicine Lodge' },
      { name: 'Barton', city: 'Great Bend' },
      { name: 'Bourbon', city: 'Fort Scott' },
      { name: 'Brown', city: 'Hiawatha' },
      { name: 'Butler', city: 'El Dorado' },
      { name: 'Chase', city: 'Cottonwood Falls' },
      { name: 'Chautauqua', city: 'Sedan' },
      { name: 'Cherokee', city: 'Columbus' },
      { name: 'Cheyenne', city: 'St. Francis' },
      { name: 'Clark', city: 'Ashland' },
      { name: 'Clay', city: 'Clay Center' },
      { name: 'Cloud', city: 'Concordia' },
      { name: 'Coffey', city: 'Burlington' },
      { name: 'Comanche', city: 'Coldwater' },
      { name: 'Cowley', city: 'Winfield' },
      { name: 'Crawford', city: 'Girard' },
      { name: 'Decatur', city: 'Oberlin' },
      { name: 'Dickinson', city: 'Abilene' },
      { name: 'Doniphan', city: 'Troy' },
      { name: 'Douglas', city: 'Lawrence' },
      { name: 'Edwards', city: 'Kinsley' },
      { name: 'Elk', city: 'Howard' },
      { name: 'Ellis', city: 'Hays' },
      { name: 'Ellsworth', city: 'Ellsworth' },
      { name: 'Finney', city: 'Garden City' },
      { name: 'Ford', city: 'Dodge City' },
      { name: 'Franklin', city: 'Ottawa' },
      { name: 'Geary', city: 'Junction City' },
      { name: 'Gove', city: 'Gove' },
      { name: 'Graham', city: 'Hill City' },
      { name: 'Grant', city: 'Ulysses' },
      { name: 'Gray', city: 'Cimarron' },
      { name: 'Greeley', city: 'Tribune' },
      { name: 'Greenwood', city: 'Eureka' },
      { name: 'Hamilton', city: 'Syracuse' },
      { name: 'Harper', city: 'Anthony' },
      { name: 'Harvey', city: 'Newton' },
      { name: 'Haskell', city: 'Sublette' },
      { name: 'Hodgeman', city: 'Jetmore' },
      { name: 'Jackson', city: 'Holton' },
      { name: 'Jefferson', city: 'Oskaloosa' },
      { name: 'Jewell', city: 'Mankato' },
      { name: 'Johnson', city: 'Olathe' },
      { name: 'Kearny', city: 'Lakin' },
      { name: 'Kingman', city: 'Kingman' },
      { name: 'Kiowa', city: 'Greensburg' },
      { name: 'Labette', city: 'Oswego' },
      { name: 'Lane', city: 'Dighton' },
      { name: 'Leavenworth', city: 'Leavenworth' },
      { name: 'Lincoln', city: 'Lincoln' },
      { name: 'Linn', city: 'Mound City' },
      { name: 'Logan', city: 'Oakley' },
      { name: 'Lyon', city: 'Emporia' },
      { name: 'Marion', city: 'Marion' },
      { name: 'Marshall', city: 'Marysville' },
      { name: 'McPherson', city: 'McPherson' },
      { name: 'Meade', city: 'Meade' },
      { name: 'Miami', city: 'Paola' },
      { name: 'Mitchell', city: 'Beloit' },
      { name: 'Montgomery', city: 'Independence' },
      { name: 'Morris', city: 'Council Grove' },
      { name: 'Morton', city: 'Elkhart' },
      { name: 'Nemaha', city: 'Seneca' },
      { name: 'Neosho', city: 'Erie' },
      { name: 'Ness', city: 'Ness City' },
      { name: 'Norton', city: 'Norton' },
      { name: 'Osage', city: 'Lyndon' },
      { name: 'Osborne', city: 'Osborne' },
      { name: 'Ottawa', city: 'Minneapolis' },
      { name: 'Pawnee', city: 'Larned' },
      { name: 'Phillips', city: 'Phillipsburg' },
      { name: 'Pottawatomie', city: 'Westmoreland' },
      { name: 'Pratt', city: 'Pratt' },
      { name: 'Rawlins', city: 'Atwood' },
      { name: 'Reno', city: 'Hutchinson' },
      { name: 'Republic', city: 'Belleville' },
      { name: 'Rice', city: 'Lyons' },
      { name: 'Riley', city: 'Manhattan' },
      { name: 'Rooks', city: 'Stockton' },
      { name: 'Rush', city: 'La Crosse' },
      { name: 'Russell', city: 'Russell' },
      { name: 'Saline', city: 'Salina' },
      { name: 'Scott', city: 'Scott City' },
      { name: 'Sedgwick', city: 'Wichita' },
      { name: 'Seward', city: 'Liberal' },
      { name: 'Shawnee', city: 'Topeka' },
      { name: 'Sheridan', city: 'Hoxie' },
      { name: 'Sherman', city: 'Goodland' },
      { name: 'Smith', city: 'Smith Center' },
      { name: 'Stafford', city: 'St. John' },
      { name: 'Stanton', city: 'Johnson' },
      { name: 'Stevens', city: 'Hugoton' },
      { name: 'Sumner', city: 'Wellington' },
      { name: 'Thomas', city: 'Colby' },
      { name: 'Trego', city: 'WaKeeney' },
      { name: 'Wabaunsee', city: 'Alma' },
      { name: 'Wallace', city: 'Sharon Springs' },
      { name: 'Washington', city: 'Washington' },
      { name: 'Wichita', city: 'Leoti' },
      { name: 'Wilson', city: 'Fredonia' },
      { name: 'Woodson', city: 'Yates Center' },
      { name: 'Wyandotte', city: 'Kansas City' },
    ],
  },

  // ===========================================================================
  // MINNESOTA
  // ===========================================================================
  'minnesota': {
    slug: 'minnesota',
    name: 'Minnesota',
    nameEs: 'Minnesota',
    countyCount: 87,
    additionalContent: 'Minnesota tiene una comunidad hispana en crecimiento, especialmente en Minneapolis-St. Paul, Worthington, y las áreas agrícolas del sur del estado. Los tribunales de familia en los 87 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Minnesota?',
        answer: 'Sí. En los 87 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Aitkin', city: 'Aitkin' },
      { name: 'Anoka', city: 'Anoka' },
      { name: 'Becker', city: 'Detroit Lakes' },
      { name: 'Beltrami', city: 'Bemidji' },
      { name: 'Benton', city: 'Foley' },
      { name: 'Big Stone', city: 'Ortonville' },
      { name: 'Blue Earth', city: 'Mankato' },
      { name: 'Brown', city: 'New Ulm' },
      { name: 'Carlton', city: 'Carlton' },
      { name: 'Carver', city: 'Chaska' },
      { name: 'Cass', city: 'Walker' },
      { name: 'Chippewa', city: 'Montevideo' },
      { name: 'Chisago', city: 'Center City' },
      { name: 'Clay', city: 'Moorhead' },
      { name: 'Clearwater', city: 'Bagley' },
      { name: 'Cook', city: 'Grand Marais' },
      { name: 'Cottonwood', city: 'Windom' },
      { name: 'Crow Wing', city: 'Brainerd' },
      { name: 'Dakota', city: 'Hastings' },
      { name: 'Dodge', city: 'Mantorville' },
      { name: 'Douglas', city: 'Alexandria' },
      { name: 'Faribault', city: 'Blue Earth' },
      { name: 'Fillmore', city: 'Preston' },
      { name: 'Freeborn', city: 'Albert Lea' },
      { name: 'Goodhue', city: 'Red Wing' },
      { name: 'Grant', city: 'Elbow Lake' },
      { name: 'Hennepin', city: 'Minneapolis' },
      { name: 'Houston', city: 'Caledonia' },
      { name: 'Hubbard', city: 'Park Rapids' },
      { name: 'Isanti', city: 'Cambridge' },
      { name: 'Itasca', city: 'Grand Rapids' },
      { name: 'Jackson', city: 'Jackson' },
      { name: 'Kanabec', city: 'Mora' },
      { name: 'Kandiyohi', city: 'Willmar' },
      { name: 'Kittson', city: 'Hallock' },
      { name: 'Koochiching', city: 'International Falls' },
      { name: 'Lac qui Parle', city: 'Madison' },
      { name: 'Lake', city: 'Two Harbors' },
      { name: 'Lake of the Woods', city: 'Baudette' },
      { name: 'Le Sueur', city: 'Le Center' },
      { name: 'Lincoln', city: 'Ivanhoe' },
      { name: 'Lyon', city: 'Marshall' },
      { name: 'Mahnomen', city: 'Mahnomen' },
      { name: 'Marshall', city: 'Warren' },
      { name: 'Martin', city: 'Fairmont' },
      { name: 'McLeod', city: 'Glencoe' },
      { name: 'Meeker', city: 'Litchfield' },
      { name: 'Mille Lacs', city: 'Milaca' },
      { name: 'Morrison', city: 'Little Falls' },
      { name: 'Mower', city: 'Austin' },
      { name: 'Murray', city: 'Slayton' },
      { name: 'Nicollet', city: 'St. Peter' },
      { name: 'Nobles', city: 'Worthington' },
      { name: 'Norman', city: 'Ada' },
      { name: 'Olmsted', city: 'Rochester' },
      { name: 'Otter Tail', city: 'Fergus Falls' },
      { name: 'Pennington', city: 'Thief River Falls' },
      { name: 'Pine', city: 'Pine City' },
      { name: 'Pipestone', city: 'Pipestone' },
      { name: 'Polk', city: 'Crookston' },
      { name: 'Pope', city: 'Glenwood' },
      { name: 'Ramsey', city: 'St. Paul' },
      { name: 'Red Lake', city: 'Red Lake Falls' },
      { name: 'Redwood', city: 'Redwood Falls' },
      { name: 'Renville', city: 'Olivia' },
      { name: 'Rice', city: 'Faribault' },
      { name: 'Rock', city: 'Luverne' },
      { name: 'Roseau', city: 'Roseau' },
      { name: 'St. Louis', city: 'Duluth' },
      { name: 'Scott', city: 'Shakopee' },
      { name: 'Sherburne', city: 'Elk River' },
      { name: 'Sibley', city: 'Gaylord' },
      { name: 'Stearns', city: 'St. Cloud' },
      { name: 'Steele', city: 'Owatonna' },
      { name: 'Stevens', city: 'Morris' },
      { name: 'Swift', city: 'Benson' },
      { name: 'Todd', city: 'Long Prairie' },
      { name: 'Traverse', city: 'Wheaton' },
      { name: 'Wabasha', city: 'Wabasha' },
      { name: 'Wadena', city: 'Wadena' },
      { name: 'Waseca', city: 'Waseca' },
      { name: 'Washington', city: 'Stillwater' },
      { name: 'Watonwan', city: 'St. James' },
      { name: 'Wilkin', city: 'Breckenridge' },
      { name: 'Winona', city: 'Winona' },
      { name: 'Wright', city: 'Buffalo' },
      { name: 'Yellow Medicine', city: 'Granite Falls' },
    ],
  },

  // ===========================================================================
  // MISSOURI
  // ===========================================================================
  'missouri': {
    slug: 'missouri',
    name: 'Missouri',
    nameEs: 'Misuri',
    countyCount: 115,
    additionalContent: 'Misuri tiene una comunidad hispana significativa, especialmente en Kansas City, St. Louis, y Springfield. Los tribunales de familia en los 115 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Misuri?',
        answer: 'Sí. En los 115 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adair', city: 'Kirksville' },
      { name: 'Andrew', city: 'Savannah' },
      { name: 'Atchison', city: 'Rock Port' },
      { name: 'Audrain', city: 'Mexico' },
      { name: 'Barry', city: 'Cassville' },
      { name: 'Barton', city: 'Lamar' },
      { name: 'Bates', city: 'Butler' },
      { name: 'Benton', city: 'Warsaw' },
      { name: 'Bollinger', city: 'Marble Hill' },
      { name: 'Boone', city: 'Columbia' },
      { name: 'Buchanan', city: 'St. Joseph' },
      { name: 'Butler', city: 'Poplar Bluff' },
      { name: 'Caldwell', city: 'Kingston' },
      { name: 'Callaway', city: 'Fulton' },
      { name: 'Camden', city: 'Camdenton' },
      { name: 'Cape Girardeau', city: 'Jackson' },
      { name: 'Carroll', city: 'Carrollton' },
      { name: 'Carter', city: 'Van Buren' },
      { name: 'Cass', city: 'Harrisonville' },
      { name: 'Cedar', city: 'Stockton' },
      { name: 'Chariton', city: 'Keytesville' },
      { name: 'Christian', city: 'Ozark' },
      { name: 'Clark', city: 'Kahoka' },
      { name: 'Clay', city: 'Liberty' },
      { name: 'Clinton', city: 'Plattsburg' },
      { name: 'Cole', city: 'Jefferson City' },
      { name: 'Cooper', city: 'Boonville' },
      { name: 'Crawford', city: 'Steelville' },
      { name: 'Dade', city: 'Greenfield' },
      { name: 'Dallas', city: 'Buffalo' },
      { name: 'Daviess', city: 'Gallatin' },
      { name: 'DeKalb', city: 'Maysville' },
      { name: 'Dent', city: 'Salem' },
      { name: 'Douglas', city: 'Ava' },
      { name: 'Dunklin', city: 'Kennett' },
      { name: 'Franklin', city: 'Union' },
      { name: 'Gasconade', city: 'Hermann' },
      { name: 'Gentry', city: 'Albany' },
      { name: 'Greene', city: 'Springfield' },
      { name: 'Grundy', city: 'Trenton' },
      { name: 'Harrison', city: 'Bethany' },
      { name: 'Henry', city: 'Clinton' },
      { name: 'Hickory', city: 'Hermitage' },
      { name: 'Holt', city: 'Oregon' },
      { name: 'Howard', city: 'Fayette' },
      { name: 'Howell', city: 'West Plains' },
      { name: 'Iron', city: 'Ironton' },
      { name: 'Jackson', city: 'Independence' },
      { name: 'Jasper', city: 'Carthage' },
      { name: 'Jefferson', city: 'Hillsboro' },
      { name: 'Johnson', city: 'Warrensburg' },
      { name: 'Knox', city: 'Edina' },
      { name: 'Laclede', city: 'Lebanon' },
      { name: 'Lafayette', city: 'Lexington' },
      { name: 'Lawrence', city: 'Mount Vernon' },
      { name: 'Lewis', city: 'Monticello' },
      { name: 'Lincoln', city: 'Troy' },
      { name: 'Linn', city: 'Linneus' },
      { name: 'Livingston', city: 'Chillicothe' },
      { name: 'Macon', city: 'Macon' },
      { name: 'Madison', city: 'Fredericktown' },
      { name: 'Maries', city: 'Vienna' },
      { name: 'Marion', city: 'Palmyra' },
      { name: 'McDonald', city: 'Pineville' },
      { name: 'Mercer', city: 'Princeton' },
      { name: 'Miller', city: 'Tuscumbia' },
      { name: 'Mississippi', city: 'Charleston' },
      { name: 'Moniteau', city: 'California' },
      { name: 'Monroe', city: 'Paris' },
      { name: 'Montgomery', city: 'Montgomery City' },
      { name: 'Morgan', city: 'Versailles' },
      { name: 'New Madrid', city: 'New Madrid' },
      { name: 'Newton', city: 'Neosho' },
      { name: 'Nodaway', city: 'Maryville' },
      { name: 'Oregon', city: 'Alton' },
      { name: 'Osage', city: 'Linn' },
      { name: 'Ozark', city: 'Gainesville' },
      { name: 'Pemiscot', city: 'Caruthersville' },
      { name: 'Perry', city: 'Perryville' },
      { name: 'Pettis', city: 'Sedalia' },
      { name: 'Phelps', city: 'Rolla' },
      { name: 'Pike', city: 'Bowling Green' },
      { name: 'Platte', city: 'Platte City' },
      { name: 'Polk', city: 'Bolivar' },
      { name: 'Pulaski', city: 'Waynesville' },
      { name: 'Putnam', city: 'Unionville' },
      { name: 'Ralls', city: 'New London' },
      { name: 'Randolph', city: 'Huntsville' },
      { name: 'Ray', city: 'Richmond' },
      { name: 'Reynolds', city: 'Centerville' },
      { name: 'Ripley', city: 'Doniphan' },
      { name: 'Saline', city: 'Marshall' },
      { name: 'Schuyler', city: 'Lancaster' },
      { name: 'Scotland', city: 'Memphis' },
      { name: 'Scott', city: 'Benton' },
      { name: 'Shannon', city: 'Eminence' },
      { name: 'Shelby', city: 'Shelbyville' },
      { name: 'St. Charles', city: 'St. Charles' },
      { name: 'St. Clair', city: 'Osceola' },
      { name: 'St. Francois', city: 'Farmington' },
      { name: 'St. Louis County', city: 'Clayton' },
      { name: 'St. Louis City', city: 'St. Louis' },
      { name: 'Ste. Genevieve', city: 'Ste. Genevieve' },
      { name: 'Stoddard', city: 'Bloomfield' },
      { name: 'Stone', city: 'Galena' },
      { name: 'Sullivan', city: 'Milan' },
      { name: 'Taney', city: 'Forsyth' },
      { name: 'Texas', city: 'Houston' },
      { name: 'Vernon', city: 'Nevada' },
      { name: 'Warren', city: 'Warrenton' },
      { name: 'Washington', city: 'Potosi' },
      { name: 'Wayne', city: 'Greenville' },
      { name: 'Webster', city: 'Marshfield' },
      { name: 'Worth', city: 'Grant City' },
      { name: 'Wright', city: 'Hartville' },
    ],
  },

  // ===========================================================================
  // NEBRASKA
  // ===========================================================================
  'nebraska': {
    slug: 'nebraska',
    name: 'Nebraska',
    nameEs: 'Nebraska',
    countyCount: 93,
    additionalContent: 'Nebraska tiene una comunidad hispana significativa, especialmente en Omaha, Lincoln, Grand Island, y las comunidades empacadoras de carne. Los tribunales de familia en los 93 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Nebraska?',
        answer: 'Sí. En los 93 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Hastings' },
      { name: 'Antelope', city: 'Neligh' },
      { name: 'Arthur', city: 'Arthur' },
      { name: 'Banner', city: 'Harrisburg' },
      { name: 'Blaine', city: 'Brewster' },
      { name: 'Boone', city: 'Albion' },
      { name: 'Box Butte', city: 'Alliance' },
      { name: 'Boyd', city: 'Butte' },
      { name: 'Brown', city: 'Ainsworth' },
      { name: 'Buffalo', city: 'Kearney' },
      { name: 'Burt', city: 'Tekamah' },
      { name: 'Butler', city: 'David City' },
      { name: 'Cass', city: 'Plattsmouth' },
      { name: 'Cedar', city: 'Hartington' },
      { name: 'Chase', city: 'Imperial' },
      { name: 'Cherry', city: 'Valentine' },
      { name: 'Cheyenne', city: 'Sidney' },
      { name: 'Clay', city: 'Clay Center' },
      { name: 'Colfax', city: 'Schuyler' },
      { name: 'Cuming', city: 'West Point' },
      { name: 'Custer', city: 'Broken Bow' },
      { name: 'Dakota', city: 'Dakota City' },
      { name: 'Dawes', city: 'Chadron' },
      { name: 'Dawson', city: 'Lexington' },
      { name: 'Deuel', city: 'Chappell' },
      { name: 'Dixon', city: 'Ponca' },
      { name: 'Dodge', city: 'Fremont' },
      { name: 'Douglas', city: 'Omaha' },
      { name: 'Dundy', city: 'Benkelman' },
      { name: 'Fillmore', city: 'Geneva' },
      { name: 'Franklin', city: 'Franklin' },
      { name: 'Frontier', city: 'Stockville' },
      { name: 'Furnas', city: 'Beaver City' },
      { name: 'Gage', city: 'Beatrice' },
      { name: 'Garden', city: 'Oshkosh' },
      { name: 'Garfield', city: 'Burwell' },
      { name: 'Gosper', city: 'Elwood' },
      { name: 'Grant', city: 'Hyannis' },
      { name: 'Greeley', city: 'Greeley' },
      { name: 'Hall', city: 'Grand Island' },
      { name: 'Hamilton', city: 'Aurora' },
      { name: 'Harlan', city: 'Alma' },
      { name: 'Hayes', city: 'Hayes Center' },
      { name: 'Hitchcock', city: 'Trenton' },
      { name: 'Holt', city: "O'Neill" },
      { name: 'Hooker', city: 'Mullen' },
      { name: 'Howard', city: 'St. Paul' },
      { name: 'Jefferson', city: 'Fairbury' },
      { name: 'Johnson', city: 'Tecumseh' },
      { name: 'Kearney', city: 'Minden' },
      { name: 'Keith', city: 'Ogallala' },
      { name: 'Keya Paha', city: 'Springview' },
      { name: 'Kimball', city: 'Kimball' },
      { name: 'Knox', city: 'Center' },
      { name: 'Lancaster', city: 'Lincoln' },
      { name: 'Lincoln', city: 'North Platte' },
      { name: 'Logan', city: 'Stapleton' },
      { name: 'Loup', city: 'Taylor' },
      { name: 'Madison', city: 'Madison' },
      { name: 'McPherson', city: 'Tryon' },
      { name: 'Merrick', city: 'Central City' },
      { name: 'Morrill', city: 'Bridgeport' },
      { name: 'Nance', city: 'Fullerton' },
      { name: 'Nemaha', city: 'Auburn' },
      { name: 'Nuckolls', city: 'Nelson' },
      { name: 'Otoe', city: 'Nebraska City' },
      { name: 'Pawnee', city: 'Pawnee City' },
      { name: 'Perkins', city: 'Grant' },
      { name: 'Phelps', city: 'Holdrege' },
      { name: 'Pierce', city: 'Pierce' },
      { name: 'Platte', city: 'Columbus' },
      { name: 'Polk', city: 'Osceola' },
      { name: 'Red Willow', city: 'McCook' },
      { name: 'Richardson', city: 'Falls City' },
      { name: 'Rock', city: 'Bassett' },
      { name: 'Saline', city: 'Wilber' },
      { name: 'Sarpy', city: 'Papillion' },
      { name: 'Saunders', city: 'Wahoo' },
      { name: 'Scotts Bluff', city: 'Gering' },
      { name: 'Seward', city: 'Seward' },
      { name: 'Sheridan', city: 'Rushville' },
      { name: 'Sherman', city: 'Loup City' },
      { name: 'Sioux', city: 'Harrison' },
      { name: 'Stanton', city: 'Stanton' },
      { name: 'Thayer', city: 'Hebron' },
      { name: 'Thomas', city: 'Thedford' },
      { name: 'Thurston', city: 'Pender' },
      { name: 'Valley', city: 'Ord' },
      { name: 'Washington', city: 'Blair' },
      { name: 'Wayne', city: 'Wayne' },
      { name: 'Webster', city: 'Red Cloud' },
      { name: 'Wheeler', city: 'Bartlett' },
      { name: 'York', city: 'York' },
    ],
  },

  // ===========================================================================
  // NORTH DAKOTA
  // ===========================================================================
  'north-dakota': {
    slug: 'north-dakota',
    name: 'North Dakota',
    nameEs: 'Dakota del Norte',
    countyCount: 53,
    additionalContent: 'Dakota del Norte tiene una comunidad hispana en crecimiento, especialmente en Fargo, Bismarck, y las comunidades agrícolas del este del estado. Los tribunales de familia en los 53 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Dakota del Norte?',
        answer: 'Sí. En los 53 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Hettinger' },
      { name: 'Barnes', city: 'Valley City' },
      { name: 'Benson', city: 'Minnewaukan' },
      { name: 'Billings', city: 'Medora' },
      { name: 'Bottineau', city: 'Bottineau' },
      { name: 'Bowman', city: 'Bowman' },
      { name: 'Burke', city: 'Bowbells' },
      { name: 'Burleigh', city: 'Bismarck' },
      { name: 'Cass', city: 'Fargo' },
      { name: 'Cavalier', city: 'Langdon' },
      { name: 'Dickey', city: 'Ellendale' },
      { name: 'Divide', city: 'Crosby' },
      { name: 'Dunn', city: 'Manning' },
      { name: 'Eddy', city: 'New Rockford' },
      { name: 'Emmons', city: 'Linton' },
      { name: 'Foster', city: 'Carrington' },
      { name: 'Golden Valley', city: 'Beach' },
      { name: 'Grand Forks', city: 'Grand Forks' },
      { name: 'Grant', city: 'Carson' },
      { name: 'Griggs', city: 'Cooperstown' },
      { name: 'Hettinger', city: 'Mott' },
      { name: 'Kidder', city: 'Steele' },
      { name: 'LaMoure', city: 'LaMoure' },
      { name: 'Logan', city: 'Napoleon' },
      { name: 'McHenry', city: 'Towner' },
      { name: 'McIntosh', city: 'Ashley' },
      { name: 'McKenzie', city: 'Watford City' },
      { name: 'McLean', city: 'Washburn' },
      { name: 'Mercer', city: 'Stanton' },
      { name: 'Morton', city: 'Mandan' },
      { name: 'Mountrail', city: 'Stanley' },
      { name: 'Nelson', city: 'Lakota' },
      { name: 'Oliver', city: 'Center' },
      { name: 'Pembina', city: 'Cavalier' },
      { name: 'Pierce', city: 'Rugby' },
      { name: 'Ramsey', city: 'Devils Lake' },
      { name: 'Ransom', city: 'Lisbon' },
      { name: 'Renville', city: 'Mohall' },
      { name: 'Richland', city: 'Wahpeton' },
      { name: 'Rolette', city: 'Rolla' },
      { name: 'Sargent', city: 'Forman' },
      { name: 'Sheridan', city: 'McClusky' },
      { name: 'Sioux', city: 'Fort Yates' },
      { name: 'Slope', city: 'Amidon' },
      { name: 'Stark', city: 'Dickinson' },
      { name: 'Steele', city: 'Finley' },
      { name: 'Stutsman', city: 'Jamestown' },
      { name: 'Towner', city: 'Cando' },
      { name: 'Traill', city: 'Hillsboro' },
      { name: 'Walsh', city: 'Grafton' },
      { name: 'Ward', city: 'Minot' },
      { name: 'Wells', city: 'Fessenden' },
      { name: 'Williams', city: 'Williston' },
    ],
  },

  // ===========================================================================
  // SOUTH DAKOTA
  // ===========================================================================
  'south-dakota': {
    slug: 'south-dakota',
    name: 'South Dakota',
    nameEs: 'Dakota del Sur',
    countyCount: 66,
    additionalContent: 'Dakota del Sur tiene una comunidad hispana en crecimiento, especialmente en Sioux Falls, Rapid City, y las comunidades agrícolas del este del estado. Los tribunales de familia en los 66 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Dakota del Sur?',
        answer: 'Sí. En los 66 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Aurora', city: 'Plankinton' },
      { name: 'Beadle', city: 'Huron' },
      { name: 'Bennett', city: 'Martin' },
      { name: 'Bon Homme', city: 'Tyndall' },
      { name: 'Brookings', city: 'Brookings' },
      { name: 'Brown', city: 'Aberdeen' },
      { name: 'Brule', city: 'Chamberlain' },
      { name: 'Buffalo', city: 'Gann Valley' },
      { name: 'Butte', city: 'Belle Fourche' },
      { name: 'Campbell', city: 'Mound City' },
      { name: 'Charles Mix', city: 'Lake Andes' },
      { name: 'Clark', city: 'Clark' },
      { name: 'Clay', city: 'Vermillion' },
      { name: 'Codington', city: 'Watertown' },
      { name: 'Corson', city: 'McIntosh' },
      { name: 'Custer', city: 'Custer' },
      { name: 'Davison', city: 'Mitchell' },
      { name: 'Day', city: 'Webster' },
      { name: 'Deuel', city: 'Clear Lake' },
      { name: 'Dewey', city: 'Timber Lake' },
      { name: 'Douglas', city: 'Armour' },
      { name: 'Edmunds', city: 'Ipswich' },
      { name: 'Fall River', city: 'Hot Springs' },
      { name: 'Faulk', city: 'Faulkton' },
      { name: 'Grant', city: 'Milbank' },
      { name: 'Gregory', city: 'Burke' },
      { name: 'Haakon', city: 'Philip' },
      { name: 'Hamlin', city: 'Hayti' },
      { name: 'Hand', city: 'Miller' },
      { name: 'Hanson', city: 'Alexandria' },
      { name: 'Harding', city: 'Buffalo' },
      { name: 'Hughes', city: 'Pierre' },
      { name: 'Hutchinson', city: 'Olivet' },
      { name: 'Hyde', city: 'Highmore' },
      { name: 'Jackson', city: 'Kadoka' },
      { name: 'Jerauld', city: 'Wessington Springs' },
      { name: 'Jones', city: 'Murdo' },
      { name: 'Kingsbury', city: 'De Smet' },
      { name: 'Lake', city: 'Madison' },
      { name: 'Lawrence', city: 'Deadwood' },
      { name: 'Lincoln', city: 'Canton' },
      { name: 'Lyman', city: 'Kennebec' },
      { name: 'Marshall', city: 'Britton' },
      { name: 'McCook', city: 'Salem' },
      { name: 'McPherson', city: 'Leola' },
      { name: 'Meade', city: 'Sturgis' },
      { name: 'Mellette', city: 'White River' },
      { name: 'Miner', city: 'Howard' },
      { name: 'Minnehaha', city: 'Sioux Falls' },
      { name: 'Moody', city: 'Flandreau' },
      { name: 'Pennington', city: 'Rapid City' },
      { name: 'Perkins', city: 'Bison' },
      { name: 'Potter', city: 'Gettysburg' },
      { name: 'Roberts', city: 'Sisseton' },
      { name: 'Sanborn', city: 'Woonsocket' },
      { name: 'Spink', city: 'Redfield' },
      { name: 'Stanley', city: 'Fort Pierre' },
      { name: 'Sully', city: 'Onida' },
      { name: 'Todd', city: 'Mission' },
      { name: 'Tripp', city: 'Winner' },
      { name: 'Turner', city: 'Parker' },
      { name: 'Union', city: 'Elk Point' },
      { name: 'Walworth', city: 'Selby' },
      { name: 'Yankton', city: 'Yankton' },
      { name: 'Ziebach', city: 'Dupree' },
      { name: 'Oglala Lakota', city: 'Pine Ridge' },
    ],
  },
};
