/**
 * Midwest East Region
 * States: Illinois, Indiana, Michigan, Ohio, Wisconsin
 * 5 states, ~437 counties
 */

import type { StateData } from './types';

export const midwestEastStates: Record<string, StateData> = {
  // ===========================================================================
  // ILLINOIS
  // ===========================================================================
  'illinois': {
    slug: 'illinois',
    name: 'Illinois',
    nameEs: 'Illinois',
    countyCount: 102,
    additionalContent: 'Illinois tiene una comunidad hispana grande y diversa, especialmente en Chicago, Aurora, Elgin, y Cicero. Los tribunales de familia en los 102 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Illinois?',
        answer: 'Sí. En los 102 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Quincy' },
      { name: 'Alexander', city: 'Cairo' },
      { name: 'Bond', city: 'Greenville' },
      { name: 'Boone', city: 'Belvidere' },
      { name: 'Brown', city: 'Mount Sterling' },
      { name: 'Bureau', city: 'Princeton' },
      { name: 'Calhoun', city: 'Hardin' },
      { name: 'Carroll', city: 'Mount Carroll' },
      { name: 'Cass', city: 'Virginia' },
      { name: 'Champaign', city: 'Urbana' },
      { name: 'Christian', city: 'Taylorville' },
      { name: 'Clark', city: 'Marshall' },
      { name: 'Clay', city: 'Louisville' },
      { name: 'Clinton', city: 'Carlyle' },
      { name: 'Coles', city: 'Charleston' },
      { name: 'Cook', city: 'Chicago' },
      { name: 'Crawford', city: 'Robinson' },
      { name: 'Cumberland', city: 'Toledo' },
      { name: 'DeKalb', city: 'Sycamore' },
      { name: 'DeWitt', city: 'Clinton' },
      { name: 'Douglas', city: 'Tuscola' },
      { name: 'DuPage', city: 'Wheaton' },
      { name: 'Edgar', city: 'Paris' },
      { name: 'Edwards', city: 'Albion' },
      { name: 'Effingham', city: 'Effingham' },
      { name: 'Fayette', city: 'Vandalia' },
      { name: 'Ford', city: 'Paxton' },
      { name: 'Franklin', city: 'Benton' },
      { name: 'Fulton', city: 'Lewistown' },
      { name: 'Gallatin', city: 'Shawneetown' },
      { name: 'Greene', city: 'Carrollton' },
      { name: 'Grundy', city: 'Morris' },
      { name: 'Hamilton', city: 'McLeansboro' },
      { name: 'Hancock', city: 'Carthage' },
      { name: 'Hardin', city: 'Elizabethtown' },
      { name: 'Henderson', city: 'Oquawka' },
      { name: 'Henry', city: 'Cambridge' },
      { name: 'Iroquois', city: 'Watseka' },
      { name: 'Jackson', city: 'Murphysboro' },
      { name: 'Jasper', city: 'Newton' },
      { name: 'Jefferson', city: 'Mount Vernon' },
      { name: 'Jersey', city: 'Jerseyville' },
      { name: 'Jo Daviess', city: 'Galena' },
      { name: 'Johnson', city: 'Vienna' },
      { name: 'Kane', city: 'Geneva' },
      { name: 'Kankakee', city: 'Kankakee' },
      { name: 'Kendall', city: 'Yorkville' },
      { name: 'Knox', city: 'Galesburg' },
      { name: 'Lake', city: 'Waukegan' },
      { name: 'LaSalle', city: 'Ottawa' },
      { name: 'Lawrence', city: 'Lawrenceville' },
      { name: 'Lee', city: 'Dixon' },
      { name: 'Livingston', city: 'Pontiac' },
      { name: 'Logan', city: 'Lincoln' },
      { name: 'Macon', city: 'Decatur' },
      { name: 'Macoupin', city: 'Carlinville' },
      { name: 'Madison', city: 'Edwardsville' },
      { name: 'Marion', city: 'Salem' },
      { name: 'Marshall', city: 'Lacon' },
      { name: 'Mason', city: 'Havana' },
      { name: 'Massac', city: 'Metropolis' },
      { name: 'McDonough', city: 'Macomb' },
      { name: 'McHenry', city: 'Woodstock' },
      { name: 'McLean', city: 'Bloomington' },
      { name: 'Menard', city: 'Petersburg' },
      { name: 'Mercer', city: 'Aledo' },
      { name: 'Monroe', city: 'Waterloo' },
      { name: 'Montgomery', city: 'Hillsboro' },
      { name: 'Morgan', city: 'Jacksonville' },
      { name: 'Moultrie', city: 'Sullivan' },
      { name: 'Ogle', city: 'Oregon' },
      { name: 'Peoria', city: 'Peoria' },
      { name: 'Perry', city: 'Pinckneyville' },
      { name: 'Piatt', city: 'Monticello' },
      { name: 'Pike', city: 'Pittsfield' },
      { name: 'Pope', city: 'Golconda' },
      { name: 'Pulaski', city: 'Mound City' },
      { name: 'Putnam', city: 'Hennepin' },
      { name: 'Randolph', city: 'Chester' },
      { name: 'Richland', city: 'Olney' },
      { name: 'Rock Island', city: 'Rock Island' },
      { name: 'Saline', city: 'Harrisburg' },
      { name: 'Sangamon', city: 'Springfield' },
      { name: 'Schuyler', city: 'Rushville' },
      { name: 'Scott', city: 'Winchester' },
      { name: 'Shelby', city: 'Shelbyville' },
      { name: 'St. Clair', city: 'Belleville' },
      { name: 'Stark', city: 'Toulon' },
      { name: 'Stephenson', city: 'Freeport' },
      { name: 'Tazewell', city: 'Pekin' },
      { name: 'Union', city: 'Jonesboro' },
      { name: 'Vermilion', city: 'Danville' },
      { name: 'Wabash', city: 'Mount Carmel' },
      { name: 'Warren', city: 'Monmouth' },
      { name: 'Washington', city: 'Nashville' },
      { name: 'Wayne', city: 'Fairfield' },
      { name: 'White', city: 'Carmi' },
      { name: 'Whiteside', city: 'Morrison' },
      { name: 'Will', city: 'Joliet' },
      { name: 'Williamson', city: 'Marion' },
      { name: 'Winnebago', city: 'Rockford' },
      { name: 'Woodford', city: 'Eureka' },
    ],
  },

  // ===========================================================================
  // INDIANA
  // ===========================================================================
  'indiana': {
    slug: 'indiana',
    name: 'Indiana',
    nameEs: 'Indiana',
    countyCount: 92,
    additionalContent: 'Indiana tiene una comunidad hispana en crecimiento, especialmente en Indianapolis, East Chicago, Hammond, y Fort Wayne. Los tribunales de familia en los 92 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Indiana?',
        answer: 'Sí. En los 92 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Decatur' },
      { name: 'Allen', city: 'Fort Wayne' },
      { name: 'Bartholomew', city: 'Columbus' },
      { name: 'Benton', city: 'Fowler' },
      { name: 'Blackford', city: 'Hartford City' },
      { name: 'Boone', city: 'Lebanon' },
      { name: 'Brown', city: 'Nashville' },
      { name: 'Carroll', city: 'Delphi' },
      { name: 'Cass', city: 'Logansport' },
      { name: 'Clark', city: 'Jeffersonville' },
      { name: 'Clay', city: 'Brazil' },
      { name: 'Clinton', city: 'Frankfort' },
      { name: 'Crawford', city: 'English' },
      { name: 'Daviess', city: 'Washington' },
      { name: 'Dearborn', city: 'Lawrenceburg' },
      { name: 'Decatur', city: 'Greensburg' },
      { name: 'DeKalb', city: 'Auburn' },
      { name: 'Delaware', city: 'Muncie' },
      { name: 'Dubois', city: 'Jasper' },
      { name: 'Elkhart', city: 'Goshen' },
      { name: 'Fayette', city: 'Connersville' },
      { name: 'Floyd', city: 'New Albany' },
      { name: 'Fountain', city: 'Covington' },
      { name: 'Franklin', city: 'Brookville' },
      { name: 'Fulton', city: 'Rochester' },
      { name: 'Gibson', city: 'Princeton' },
      { name: 'Grant', city: 'Marion' },
      { name: 'Greene', city: 'Bloomfield' },
      { name: 'Hamilton', city: 'Noblesville' },
      { name: 'Hancock', city: 'Greenfield' },
      { name: 'Harrison', city: 'Corydon' },
      { name: 'Hendricks', city: 'Danville' },
      { name: 'Henry', city: 'New Castle' },
      { name: 'Howard', city: 'Kokomo' },
      { name: 'Huntington', city: 'Huntington' },
      { name: 'Jackson', city: 'Brownstown' },
      { name: 'Jasper', city: 'Rensselaer' },
      { name: 'Jay', city: 'Portland' },
      { name: 'Jefferson', city: 'Madison' },
      { name: 'Jennings', city: 'Vernon' },
      { name: 'Johnson', city: 'Franklin' },
      { name: 'Knox', city: 'Vincennes' },
      { name: 'Kosciusko', city: 'Warsaw' },
      { name: 'LaGrange', city: 'LaGrange' },
      { name: 'Lake', city: 'Crown Point' },
      { name: 'LaPorte', city: 'La Porte' },
      { name: 'Lawrence', city: 'Bedford' },
      { name: 'Madison', city: 'Anderson' },
      { name: 'Marion', city: 'Indianapolis' },
      { name: 'Marshall', city: 'Plymouth' },
      { name: 'Martin', city: 'Shoals' },
      { name: 'Miami', city: 'Peru' },
      { name: 'Monroe', city: 'Bloomington' },
      { name: 'Montgomery', city: 'Crawfordsville' },
      { name: 'Morgan', city: 'Martinsville' },
      { name: 'Newton', city: 'Kentland' },
      { name: 'Noble', city: 'Albion' },
      { name: 'Ohio', city: 'Rising Sun' },
      { name: 'Orange', city: 'Paoli' },
      { name: 'Owen', city: 'Spencer' },
      { name: 'Parke', city: 'Rockville' },
      { name: 'Perry', city: 'Tell City' },
      { name: 'Pike', city: 'Petersburg' },
      { name: 'Porter', city: 'Valparaiso' },
      { name: 'Posey', city: 'Mount Vernon' },
      { name: 'Pulaski', city: 'Winamac' },
      { name: 'Putnam', city: 'Greencastle' },
      { name: 'Randolph', city: 'Winchester' },
      { name: 'Ripley', city: 'Versailles' },
      { name: 'Rush', city: 'Rushville' },
      { name: 'St. Joseph', city: 'South Bend' },
      { name: 'Scott', city: 'Scottsburg' },
      { name: 'Shelby', city: 'Shelbyville' },
      { name: 'Spencer', city: 'Rockport' },
      { name: 'Starke', city: 'Knox' },
      { name: 'Steuben', city: 'Angola' },
      { name: 'Sullivan', city: 'Sullivan' },
      { name: 'Switzerland', city: 'Vevay' },
      { name: 'Tippecanoe', city: 'Lafayette' },
      { name: 'Tipton', city: 'Tipton' },
      { name: 'Union', city: 'Liberty' },
      { name: 'Vanderburgh', city: 'Evansville' },
      { name: 'Vermillion', city: 'Newport' },
      { name: 'Vigo', city: 'Terre Haute' },
      { name: 'Wabash', city: 'Wabash' },
      { name: 'Warren', city: 'Williamsport' },
      { name: 'Warrick', city: 'Boonville' },
      { name: 'Washington', city: 'Salem' },
      { name: 'Wayne', city: 'Richmond' },
      { name: 'Wells', city: 'Bluffton' },
      { name: 'White', city: 'Monticello' },
      { name: 'Whitley', city: 'Columbia City' },
    ],
  },

  // ===========================================================================
  // MICHIGAN
  // ===========================================================================
  'michigan': {
    slug: 'michigan',
    name: 'Michigan',
    nameEs: 'Míchigan',
    countyCount: 83,
    additionalContent: 'Míchigan tiene una comunidad hispana significativa, especialmente en Detroit, Grand Rapids, Lansing, y las áreas agrícolas del suroeste del estado. Los tribunales de familia en los 83 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Míchigan?',
        answer: 'Sí. En los 83 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Alcona', city: 'Harrisville' },
      { name: 'Alger', city: 'Munising' },
      { name: 'Allegan', city: 'Allegan' },
      { name: 'Alpena', city: 'Alpena' },
      { name: 'Antrim', city: 'Bellaire' },
      { name: 'Arenac', city: 'Standish' },
      { name: 'Baraga', city: "L'Anse" },
      { name: 'Barry', city: 'Hastings' },
      { name: 'Bay', city: 'Bay City' },
      { name: 'Benzie', city: 'Beulah' },
      { name: 'Berrien', city: 'St. Joseph' },
      { name: 'Branch', city: 'Coldwater' },
      { name: 'Calhoun', city: 'Marshall' },
      { name: 'Cass', city: 'Cassopolis' },
      { name: 'Charlevoix', city: 'Charlevoix' },
      { name: 'Cheboygan', city: 'Cheboygan' },
      { name: 'Chippewa', city: 'Sault Ste. Marie' },
      { name: 'Clare', city: 'Harrison' },
      { name: 'Clinton', city: 'St. Johns' },
      { name: 'Crawford', city: 'Grayling' },
      { name: 'Delta', city: 'Escanaba' },
      { name: 'Dickinson', city: 'Iron Mountain' },
      { name: 'Eaton', city: 'Charlotte' },
      { name: 'Emmet', city: 'Petoskey' },
      { name: 'Genesee', city: 'Flint' },
      { name: 'Gladwin', city: 'Gladwin' },
      { name: 'Gogebic', city: 'Bessemer' },
      { name: 'Grand Traverse', city: 'Traverse City' },
      { name: 'Gratiot', city: 'Ithaca' },
      { name: 'Hillsdale', city: 'Hillsdale' },
      { name: 'Houghton', city: 'Houghton' },
      { name: 'Huron', city: 'Bad Axe' },
      { name: 'Ingham', city: 'Mason' },
      { name: 'Ionia', city: 'Ionia' },
      { name: 'Iosco', city: 'Tawas City' },
      { name: 'Iron', city: 'Crystal Falls' },
      { name: 'Isabella', city: 'Mount Pleasant' },
      { name: 'Jackson', city: 'Jackson' },
      { name: 'Kalamazoo', city: 'Kalamazoo' },
      { name: 'Kalkaska', city: 'Kalkaska' },
      { name: 'Kent', city: 'Grand Rapids' },
      { name: 'Keweenaw', city: 'Eagle River' },
      { name: 'Lake', city: 'Baldwin' },
      { name: 'Lapeer', city: 'Lapeer' },
      { name: 'Leelanau', city: 'Leland' },
      { name: 'Lenawee', city: 'Adrian' },
      { name: 'Livingston', city: 'Howell' },
      { name: 'Luce', city: 'Newberry' },
      { name: 'Mackinac', city: 'St. Ignace' },
      { name: 'Macomb', city: 'Mount Clemens' },
      { name: 'Manistee', city: 'Manistee' },
      { name: 'Marquette', city: 'Marquette' },
      { name: 'Mason', city: 'Ludington' },
      { name: 'Mecosta', city: 'Big Rapids' },
      { name: 'Menominee', city: 'Menominee' },
      { name: 'Midland', city: 'Midland' },
      { name: 'Missaukee', city: 'Lake City' },
      { name: 'Monroe', city: 'Monroe' },
      { name: 'Montcalm', city: 'Stanton' },
      { name: 'Montmorency', city: 'Atlanta' },
      { name: 'Muskegon', city: 'Muskegon' },
      { name: 'Newaygo', city: 'White Cloud' },
      { name: 'Oakland', city: 'Pontiac' },
      { name: 'Oceana', city: 'Hart' },
      { name: 'Ogemaw', city: 'West Branch' },
      { name: 'Ontonagon', city: 'Ontonagon' },
      { name: 'Osceola', city: 'Reed City' },
      { name: 'Oscoda', city: 'Mio' },
      { name: 'Otsego', city: 'Gaylord' },
      { name: 'Ottawa', city: 'Grand Haven' },
      { name: 'Presque Isle', city: 'Rogers City' },
      { name: 'Roscommon', city: 'Roscommon' },
      { name: 'Saginaw', city: 'Saginaw' },
      { name: 'St. Clair', city: 'Port Huron' },
      { name: 'St. Joseph', city: 'Centreville' },
      { name: 'Sanilac', city: 'Sandusky' },
      { name: 'Schoolcraft', city: 'Manistique' },
      { name: 'Shiawassee', city: 'Corunna' },
      { name: 'Tuscola', city: 'Caro' },
      { name: 'Van Buren', city: 'Paw Paw' },
      { name: 'Washtenaw', city: 'Ann Arbor' },
      { name: 'Wayne', city: 'Detroit' },
      { name: 'Wexford', city: 'Cadillac' },
    ],
  },

  // ===========================================================================
  // OHIO
  // ===========================================================================
  'ohio': {
    slug: 'ohio',
    name: 'Ohio',
    nameEs: 'Ohio',
    countyCount: 88,
    additionalContent: 'Ohio tiene una comunidad hispana significativa, especialmente en Cleveland, Columbus, Cincinnati, y Toledo. Los tribunales de familia en los 88 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Ohio?',
        answer: 'Sí. En los 88 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'West Union' },
      { name: 'Allen', city: 'Lima' },
      { name: 'Ashland', city: 'Ashland' },
      { name: 'Ashtabula', city: 'Jefferson' },
      { name: 'Athens', city: 'Athens' },
      { name: 'Auglaize', city: 'Wapakoneta' },
      { name: 'Belmont', city: 'St. Clairsville' },
      { name: 'Brown', city: 'Georgetown' },
      { name: 'Butler', city: 'Hamilton' },
      { name: 'Carroll', city: 'Carrollton' },
      { name: 'Champaign', city: 'Urbana' },
      { name: 'Clark', city: 'Springfield' },
      { name: 'Clermont', city: 'Batavia' },
      { name: 'Clinton', city: 'Wilmington' },
      { name: 'Columbiana', city: 'Lisbon' },
      { name: 'Coshocton', city: 'Coshocton' },
      { name: 'Crawford', city: 'Bucyrus' },
      { name: 'Cuyahoga', city: 'Cleveland' },
      { name: 'Darke', city: 'Greenville' },
      { name: 'Defiance', city: 'Defiance' },
      { name: 'Delaware', city: 'Delaware' },
      { name: 'Erie', city: 'Sandusky' },
      { name: 'Fairfield', city: 'Lancaster' },
      { name: 'Fayette', city: 'Washington Court House' },
      { name: 'Franklin', city: 'Columbus' },
      { name: 'Fulton', city: 'Wauseon' },
      { name: 'Gallia', city: 'Gallipolis' },
      { name: 'Geauga', city: 'Chardon' },
      { name: 'Greene', city: 'Xenia' },
      { name: 'Guernsey', city: 'Cambridge' },
      { name: 'Hamilton', city: 'Cincinnati' },
      { name: 'Hancock', city: 'Findlay' },
      { name: 'Hardin', city: 'Kenton' },
      { name: 'Harrison', city: 'Cadiz' },
      { name: 'Henry', city: 'Napoleon' },
      { name: 'Highland', city: 'Hillsboro' },
      { name: 'Hocking', city: 'Logan' },
      { name: 'Holmes', city: 'Millersburg' },
      { name: 'Huron', city: 'Norwalk' },
      { name: 'Jackson', city: 'Jackson' },
      { name: 'Jefferson', city: 'Steubenville' },
      { name: 'Knox', city: 'Mount Vernon' },
      { name: 'Lake', city: 'Painesville' },
      { name: 'Lawrence', city: 'Ironton' },
      { name: 'Licking', city: 'Newark' },
      { name: 'Logan', city: 'Bellefontaine' },
      { name: 'Lorain', city: 'Elyria' },
      { name: 'Lucas', city: 'Toledo' },
      { name: 'Madison', city: 'London' },
      { name: 'Mahoning', city: 'Youngstown' },
      { name: 'Marion', city: 'Marion' },
      { name: 'Medina', city: 'Medina' },
      { name: 'Meigs', city: 'Pomeroy' },
      { name: 'Mercer', city: 'Celina' },
      { name: 'Miami', city: 'Troy' },
      { name: 'Monroe', city: 'Woodsfield' },
      { name: 'Montgomery', city: 'Dayton' },
      { name: 'Morgan', city: 'McConnelsville' },
      { name: 'Morrow', city: 'Mount Gilead' },
      { name: 'Muskingum', city: 'Zanesville' },
      { name: 'Noble', city: 'Caldwell' },
      { name: 'Ottawa', city: 'Port Clinton' },
      { name: 'Paulding', city: 'Paulding' },
      { name: 'Perry', city: 'New Lexington' },
      { name: 'Pickaway', city: 'Circleville' },
      { name: 'Pike', city: 'Waverly' },
      { name: 'Portage', city: 'Ravenna' },
      { name: 'Preble', city: 'Eaton' },
      { name: 'Putnam', city: 'Ottawa' },
      { name: 'Richland', city: 'Mansfield' },
      { name: 'Ross', city: 'Chillicothe' },
      { name: 'Sandusky', city: 'Fremont' },
      { name: 'Scioto', city: 'Portsmouth' },
      { name: 'Seneca', city: 'Tiffin' },
      { name: 'Shelby', city: 'Sidney' },
      { name: 'Stark', city: 'Canton' },
      { name: 'Summit', city: 'Akron' },
      { name: 'Trumbull', city: 'Warren' },
      { name: 'Tuscarawas', city: 'New Philadelphia' },
      { name: 'Union', city: 'Marysville' },
      { name: 'Van Wert', city: 'Van Wert' },
      { name: 'Vinton', city: 'McArthur' },
      { name: 'Warren', city: 'Lebanon' },
      { name: 'Washington', city: 'Marietta' },
      { name: 'Wayne', city: 'Wooster' },
      { name: 'Williams', city: 'Bryan' },
      { name: 'Wood', city: 'Bowling Green' },
      { name: 'Wyandot', city: 'Upper Sandusky' },
    ],
  },

  // ===========================================================================
  // WISCONSIN
  // ===========================================================================
  'wisconsin': {
    slug: 'wisconsin',
    name: 'Wisconsin',
    nameEs: 'Wisconsin',
    countyCount: 72,
    additionalContent: 'Wisconsin tiene una comunidad hispana en crecimiento, especialmente en Milwaukee, Madison, Racine, y las áreas agrícolas del estado. Los tribunales de familia en los 72 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Wisconsin?',
        answer: 'Sí. En los 72 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Friendship' },
      { name: 'Ashland', city: 'Ashland' },
      { name: 'Barron', city: 'Barron' },
      { name: 'Bayfield', city: 'Washburn' },
      { name: 'Brown', city: 'Green Bay' },
      { name: 'Buffalo', city: 'Alma' },
      { name: 'Burnett', city: 'Siren' },
      { name: 'Calumet', city: 'Chilton' },
      { name: 'Chippewa', city: 'Chippewa Falls' },
      { name: 'Clark', city: 'Neillsville' },
      { name: 'Columbia', city: 'Portage' },
      { name: 'Crawford', city: 'Prairie du Chien' },
      { name: 'Dane', city: 'Madison' },
      { name: 'Dodge', city: 'Juneau' },
      { name: 'Door', city: 'Sturgeon Bay' },
      { name: 'Douglas', city: 'Superior' },
      { name: 'Dunn', city: 'Menomonie' },
      { name: 'Eau Claire', city: 'Eau Claire' },
      { name: 'Florence', city: 'Florence' },
      { name: 'Fond du Lac', city: 'Fond du Lac' },
      { name: 'Forest', city: 'Crandon' },
      { name: 'Grant', city: 'Lancaster' },
      { name: 'Green', city: 'Monroe' },
      { name: 'Green Lake', city: 'Green Lake' },
      { name: 'Iowa', city: 'Dodgeville' },
      { name: 'Iron', city: 'Hurley' },
      { name: 'Jackson', city: 'Black River Falls' },
      { name: 'Jefferson', city: 'Jefferson' },
      { name: 'Juneau', city: 'Mauston' },
      { name: 'Kenosha', city: 'Kenosha' },
      { name: 'Kewaunee', city: 'Kewaunee' },
      { name: 'La Crosse', city: 'La Crosse' },
      { name: 'Lafayette', city: 'Darlington' },
      { name: 'Langlade', city: 'Antigo' },
      { name: 'Lincoln', city: 'Merrill' },
      { name: 'Manitowoc', city: 'Manitowoc' },
      { name: 'Marathon', city: 'Wausau' },
      { name: 'Marinette', city: 'Marinette' },
      { name: 'Marquette', city: 'Montello' },
      { name: 'Menominee', city: 'Keshena' },
      { name: 'Milwaukee', city: 'Milwaukee' },
      { name: 'Monroe', city: 'Sparta' },
      { name: 'Oconto', city: 'Oconto' },
      { name: 'Oneida', city: 'Rhinelander' },
      { name: 'Outagamie', city: 'Appleton' },
      { name: 'Ozaukee', city: 'Port Washington' },
      { name: 'Pepin', city: 'Durand' },
      { name: 'Pierce', city: 'Ellsworth' },
      { name: 'Polk', city: 'Balsam Lake' },
      { name: 'Portage', city: 'Stevens Point' },
      { name: 'Price', city: 'Phillips' },
      { name: 'Racine', city: 'Racine' },
      { name: 'Richland', city: 'Richland Center' },
      { name: 'Rock', city: 'Janesville' },
      { name: 'Rusk', city: 'Ladysmith' },
      { name: 'St. Croix', city: 'Hudson' },
      { name: 'Sauk', city: 'Baraboo' },
      { name: 'Sawyer', city: 'Hayward' },
      { name: 'Shawano', city: 'Shawano' },
      { name: 'Sheboygan', city: 'Sheboygan' },
      { name: 'Taylor', city: 'Medford' },
      { name: 'Trempealeau', city: 'Whitehall' },
      { name: 'Vernon', city: 'Viroqua' },
      { name: 'Vilas', city: 'Eagle River' },
      { name: 'Walworth', city: 'Elkhorn' },
      { name: 'Washburn', city: 'Shell Lake' },
      { name: 'Washington', city: 'West Bend' },
      { name: 'Waukesha', city: 'Waukesha' },
      { name: 'Waupaca', city: 'Waupaca' },
      { name: 'Waushara', city: 'Wautoma' },
      { name: 'Winnebago', city: 'Oshkosh' },
      { name: 'Wood', city: 'Wisconsin Rapids' },
    ],
  },
};
