/**
 * South Atlantic Region
 * States: District of Columbia, Delaware, Florida, Georgia, Maryland, North Carolina, South Carolina, Virginia, West Virginia
 * 9 states, ~588 counties
 */

import type { StateData } from './types';

export const southAtlanticStates: Record<string, StateData> = {
  // ===========================================================================
  // DISTRICT OF COLUMBIA
  // ===========================================================================
  'district-of-columbia': {
    slug: 'district-of-columbia',
    name: 'District of Columbia',
    nameEs: 'Distrito de Columbia',
    countyCount: 1,
    additionalContent: 'El Distrito de Columbia tiene una comunidad hispana vibrante y diversa. El Tribunal Superior del DC reconoce nuestro nombre y acepta nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales del Distrito de Columbia?',
        answer: 'Sí. En el Tribunal Superior del DC. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'District of Columbia', city: 'Washington' },
    ],
  },

  // ===========================================================================
  // DELAWARE
  // ===========================================================================
  'delaware': {
    slug: 'delaware',
    name: 'Delaware',
    nameEs: 'Delaware',
    countyCount: 3,
    additionalContent: 'Delaware tiene una comunidad hispana en crecimiento, especialmente en Wilmington y las áreas del sur del estado. Los tribunales de familia en los 3 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Delaware?',
        answer: 'Sí. En los 3 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Kent', city: 'Dover' },
      { name: 'New Castle', city: 'Wilmington' },
      { name: 'Sussex', city: 'Georgetown' },
    ],
  },

  // ===========================================================================
  // FLORIDA
  // ===========================================================================
  'florida': {
    slug: 'florida',
    name: 'Florida',
    nameEs: 'Florida',
    countyCount: 67,
    additionalContent: 'Florida tiene una de las poblaciones hispanas más grandes del país, especialmente en Miami, Orlando, Tampa, y Jacksonville. Los tribunales de familia en los 67 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Florida?',
        answer: 'Sí. En los 67 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Alachua', city: 'Gainesville' },
      { name: 'Baker', city: 'Macclenny' },
      { name: 'Bay', city: 'Panama City' },
      { name: 'Bradford', city: 'Starke' },
      { name: 'Brevard', city: 'Titusville' },
      { name: 'Broward', city: 'Fort Lauderdale' },
      { name: 'Calhoun', city: 'Blountstown' },
      { name: 'Charlotte', city: 'Punta Gorda' },
      { name: 'Citrus', city: 'Inverness' },
      { name: 'Clay', city: 'Green Cove Springs' },
      { name: 'Collier', city: 'Naples' },
      { name: 'Columbia', city: 'Lake City' },
      { name: 'DeSoto', city: 'Arcadia' },
      { name: 'Dixie', city: 'Cross City' },
      { name: 'Duval', city: 'Jacksonville' },
      { name: 'Escambia', city: 'Pensacola' },
      { name: 'Flagler', city: 'Bunnell' },
      { name: 'Franklin', city: 'Apalachicola' },
      { name: 'Gadsden', city: 'Quincy' },
      { name: 'Gilchrist', city: 'Trenton' },
      { name: 'Glades', city: 'Moore Haven' },
      { name: 'Gulf', city: 'Port St. Joe' },
      { name: 'Hamilton', city: 'Jasper' },
      { name: 'Hardee', city: 'Wauchula' },
      { name: 'Hendry', city: 'LaBelle' },
      { name: 'Hernando', city: 'Brooksville' },
      { name: 'Highlands', city: 'Sebring' },
      { name: 'Hillsborough', city: 'Tampa' },
      { name: 'Holmes', city: 'Bonifay' },
      { name: 'Indian River', city: 'Vero Beach' },
      { name: 'Jackson', city: 'Marianna' },
      { name: 'Jefferson', city: 'Monticello' },
      { name: 'Lafayette', city: 'Mayo' },
      { name: 'Lake', city: 'Tavares' },
      { name: 'Lee', city: 'Fort Myers' },
      { name: 'Leon', city: 'Tallahassee' },
      { name: 'Levy', city: 'Bronson' },
      { name: 'Liberty', city: 'Bristol' },
      { name: 'Madison', city: 'Madison' },
      { name: 'Manatee', city: 'Bradenton' },
      { name: 'Marion', city: 'Ocala' },
      { name: 'Martin', city: 'Stuart' },
      { name: 'Miami-Dade', city: 'Miami' },
      { name: 'Monroe', city: 'Key West' },
      { name: 'Nassau', city: 'Fernandina Beach' },
      { name: 'Okaloosa', city: 'Crestview' },
      { name: 'Okeechobee', city: 'Okeechobee' },
      { name: 'Orange', city: 'Orlando' },
      { name: 'Osceola', city: 'Kissimmee' },
      { name: 'Palm Beach', city: 'West Palm Beach' },
      { name: 'Pasco', city: 'Dade City' },
      { name: 'Pinellas', city: 'Clearwater' },
      { name: 'Polk', city: 'Bartow' },
      { name: 'Putnam', city: 'Palatka' },
      { name: 'Santa Rosa', city: 'Milton' },
      { name: 'Sarasota', city: 'Sarasota' },
      { name: 'Seminole', city: 'Sanford' },
      { name: 'St. Johns', city: 'St. Augustine' },
      { name: 'St. Lucie', city: 'Fort Pierce' },
      { name: 'Sumter', city: 'Bushnell' },
      { name: 'Suwannee', city: 'Live Oak' },
      { name: 'Taylor', city: 'Perry' },
      { name: 'Union', city: 'Lake Butler' },
      { name: 'Volusia', city: 'DeLand' },
      { name: 'Wakulla', city: 'Crawfordville' },
      { name: 'Walton', city: 'DeFuniak Springs' },
      { name: 'Washington', city: 'Chipley' },
    ],
  },

  // ===========================================================================
  // GEORGIA
  // ===========================================================================
  'georgia': {
    slug: 'georgia',
    name: 'Georgia',
    nameEs: 'Georgia',
    countyCount: 159,
    additionalContent: 'Georgia tiene una comunidad hispana grande y diversa, especialmente en Atlanta, Dalton, Gainesville, y las áreas agrícolas del sur del estado. Los tribunales de familia en los 159 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Georgia?',
        answer: 'Sí. En los 159 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Appling', city: 'Baxley' },
      { name: 'Atkinson', city: 'Pearson' },
      { name: 'Bacon', city: 'Alma' },
      { name: 'Baker', city: 'Newton' },
      { name: 'Baldwin', city: 'Milledgeville' },
      { name: 'Banks', city: 'Homer' },
      { name: 'Barrow', city: 'Winder' },
      { name: 'Bartow', city: 'Cartersville' },
      { name: 'Ben Hill', city: 'Fitzgerald' },
      { name: 'Berrien', city: 'Nashville' },
      { name: 'Bibb', city: 'Macon' },
      { name: 'Bleckley', city: 'Cochran' },
      { name: 'Brantley', city: 'Nahunta' },
      { name: 'Brooks', city: 'Quitman' },
      { name: 'Bryan', city: 'Pembroke' },
      { name: 'Bulloch', city: 'Statesboro' },
      { name: 'Burke', city: 'Waynesboro' },
      { name: 'Butts', city: 'Jackson' },
      { name: 'Calhoun', city: 'Morgan' },
      { name: 'Camden', city: 'Woodbine' },
      { name: 'Candler', city: 'Metter' },
      { name: 'Carroll', city: 'Carrollton' },
      { name: 'Catoosa', city: 'Ringgold' },
      { name: 'Charlton', city: 'Folkston' },
      { name: 'Chatham', city: 'Savannah' },
      { name: 'Chattahoochee', city: 'Cusseta' },
      { name: 'Chattooga', city: 'Summerville' },
      { name: 'Cherokee', city: 'Canton' },
      { name: 'Clarke', city: 'Athens' },
      { name: 'Clay', city: 'Fort Gaines' },
      { name: 'Clayton', city: 'Jonesboro' },
      { name: 'Clinch', city: 'Homerville' },
      { name: 'Cobb', city: 'Marietta' },
      { name: 'Coffee', city: 'Douglas' },
      { name: 'Colquitt', city: 'Moultrie' },
      { name: 'Columbia', city: 'Evans' },
      { name: 'Cook', city: 'Adel' },
      { name: 'Coweta', city: 'Newnan' },
      { name: 'Crawford', city: 'Knoxville' },
      { name: 'Crisp', city: 'Cordele' },
      { name: 'Dade', city: 'Trenton' },
      { name: 'Dawson', city: 'Dawsonville' },
      { name: 'Decatur', city: 'Bainbridge' },
      { name: 'DeKalb', city: 'Decatur' },
      { name: 'Dodge', city: 'Eastman' },
      { name: 'Dooly', city: 'Vienna' },
      { name: 'Dougherty', city: 'Albany' },
      { name: 'Douglas', city: 'Douglasville' },
      { name: 'Early', city: 'Blakely' },
      { name: 'Echols', city: 'Statenville' },
      { name: 'Effingham', city: 'Springfield' },
      { name: 'Elbert', city: 'Elberton' },
      { name: 'Emanuel', city: 'Swainsboro' },
      { name: 'Evans', city: 'Claxton' },
      { name: 'Fannin', city: 'Blue Ridge' },
      { name: 'Fayette', city: 'Fayetteville' },
      { name: 'Floyd', city: 'Rome' },
      { name: 'Forsyth', city: 'Cumming' },
      { name: 'Franklin', city: 'Carnesville' },
      { name: 'Fulton', city: 'Atlanta' },
      { name: 'Gilmer', city: 'Ellijay' },
      { name: 'Glascock', city: 'Gibson' },
      { name: 'Glynn', city: 'Brunswick' },
      { name: 'Gordon', city: 'Calhoun' },
      { name: 'Grady', city: 'Cairo' },
      { name: 'Greene', city: 'Greensboro' },
      { name: 'Gwinnett', city: 'Lawrenceville' },
      { name: 'Habersham', city: 'Clarkesville' },
      { name: 'Hall', city: 'Gainesville' },
      { name: 'Hancock', city: 'Sparta' },
      { name: 'Haralson', city: 'Buchanan' },
      { name: 'Harris', city: 'Hamilton' },
      { name: 'Hart', city: 'Hartwell' },
      { name: 'Heard', city: 'Franklin' },
      { name: 'Henry', city: 'McDonough' },
      { name: 'Houston', city: 'Perry' },
      { name: 'Irwin', city: 'Ocilla' },
      { name: 'Jackson', city: 'Jefferson' },
      { name: 'Jasper', city: 'Monticello' },
      { name: 'Jeff Davis', city: 'Hazlehurst' },
      { name: 'Jefferson', city: 'Louisville' },
      { name: 'Jenkins', city: 'Millen' },
      { name: 'Johnson', city: 'Wrightsville' },
      { name: 'Jones', city: 'Gray' },
      { name: 'Lamar', city: 'Barnesville' },
      { name: 'Lanier', city: 'Lakeland' },
      { name: 'Laurens', city: 'Dublin' },
      { name: 'Lee', city: 'Leesburg' },
      { name: 'Liberty', city: 'Hinesville' },
      { name: 'Lincoln', city: 'Lincolnton' },
      { name: 'Long', city: 'Ludowici' },
      { name: 'Lowndes', city: 'Valdosta' },
      { name: 'Lumpkin', city: 'Dahlonega' },
      { name: 'Macon', city: 'Oglethorpe' },
      { name: 'Madison', city: 'Danielsville' },
      { name: 'Marion', city: 'Buena Vista' },
      { name: 'McDuffie', city: 'Thomson' },
      { name: 'McIntosh', city: 'Darien' },
      { name: 'Meriwether', city: 'Greenville' },
      { name: 'Miller', city: 'Colquitt' },
      { name: 'Mitchell', city: 'Camilla' },
      { name: 'Monroe', city: 'Forsyth' },
      { name: 'Montgomery', city: 'Mount Vernon' },
      { name: 'Morgan', city: 'Madison' },
      { name: 'Murray', city: 'Chatsworth' },
      { name: 'Muscogee', city: 'Columbus' },
      { name: 'Newton', city: 'Covington' },
      { name: 'Oconee', city: 'Watkinsville' },
      { name: 'Oglethorpe', city: 'Lexington' },
      { name: 'Paulding', city: 'Dallas' },
      { name: 'Peach', city: 'Fort Valley' },
      { name: 'Pickens', city: 'Jasper' },
      { name: 'Pierce', city: 'Blackshear' },
      { name: 'Pike', city: 'Zebulon' },
      { name: 'Polk', city: 'Cedartown' },
      { name: 'Pulaski', city: 'Hawkinsville' },
      { name: 'Putnam', city: 'Eatonton' },
      { name: 'Quitman', city: 'Georgetown' },
      { name: 'Rabun', city: 'Clayton' },
      { name: 'Randolph', city: 'Cuthbert' },
      { name: 'Richmond', city: 'Augusta' },
      { name: 'Rockdale', city: 'Conyers' },
      { name: 'Schley', city: 'Ellaville' },
      { name: 'Screven', city: 'Sylvania' },
      { name: 'Seminole', city: 'Donalsonville' },
      { name: 'Spalding', city: 'Griffin' },
      { name: 'Stephens', city: 'Toccoa' },
      { name: 'Stewart', city: 'Lumpkin' },
      { name: 'Sumter', city: 'Americus' },
      { name: 'Talbot', city: 'Talbotton' },
      { name: 'Taliaferro', city: 'Crawfordville' },
      { name: 'Tattnall', city: 'Reidsville' },
      { name: 'Taylor', city: 'Butler' },
      { name: 'Telfair', city: 'McRae-Helena' },
      { name: 'Terrell', city: 'Dawson' },
      { name: 'Thomas', city: 'Thomasville' },
      { name: 'Tift', city: 'Tifton' },
      { name: 'Toombs', city: 'Lyons' },
      { name: 'Towns', city: 'Hiawassee' },
      { name: 'Treutlen', city: 'Soperton' },
      { name: 'Troup', city: 'LaGrange' },
      { name: 'Turner', city: 'Ashburn' },
      { name: 'Twiggs', city: 'Jeffersonville' },
      { name: 'Union', city: 'Blairsville' },
      { name: 'Upson', city: 'Thomaston' },
      { name: 'Walker', city: 'LaFayette' },
      { name: 'Walton', city: 'Monroe' },
      { name: 'Ware', city: 'Waycross' },
      { name: 'Warren', city: 'Warrenton' },
      { name: 'Washington', city: 'Sandersville' },
      { name: 'Wayne', city: 'Jesup' },
      { name: 'Webster', city: 'Preston' },
      { name: 'Wheeler', city: 'Alamo' },
      { name: 'White', city: 'Cleveland' },
      { name: 'Whitfield', city: 'Dalton' },
      { name: 'Wilcox', city: 'Abbeville' },
      { name: 'Wilkes', city: 'Washington' },
      { name: 'Wilkinson', city: 'Irwinton' },
      { name: 'Worth', city: 'Sylvester' },
    ],
  },

  // ===========================================================================
  // MARYLAND
  // ===========================================================================
  'maryland': {
    slug: 'maryland',
    name: 'Maryland',
    nameEs: 'Maryland',
    countyCount: 24,
    additionalContent: 'Maryland tiene una comunidad hispana grande y diversa, especialmente en el área de Washington D.C., Baltimore, y Prince George\'s County. Los tribunales de familia en los 24 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Maryland?',
        answer: 'Sí. En los 24 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Allegany', city: 'Cumberland' },
      { name: 'Anne Arundel', city: 'Annapolis' },
      { name: 'Baltimore County', city: 'Towson' },
      { name: 'Baltimore City', city: 'Baltimore' },
      { name: 'Calvert', city: 'Prince Frederick' },
      { name: 'Caroline', city: 'Denton' },
      { name: 'Carroll', city: 'Westminster' },
      { name: 'Cecil', city: 'Elkton' },
      { name: 'Charles', city: 'La Plata' },
      { name: 'Dorchester', city: 'Cambridge' },
      { name: 'Frederick', city: 'Frederick' },
      { name: 'Garrett', city: 'Oakland' },
      { name: 'Harford', city: 'Bel Air' },
      { name: 'Howard', city: 'Ellicott City' },
      { name: 'Kent', city: 'Chestertown' },
      { name: 'Montgomery', city: 'Rockville' },
      { name: "Prince George's", city: 'Upper Marlboro' },
      { name: "Queen Anne's", city: 'Centreville' },
      { name: "St. Mary's", city: 'Leonardtown' },
      { name: 'Somerset', city: 'Princess Anne' },
      { name: 'Talbot', city: 'Easton' },
      { name: 'Washington', city: 'Hagerstown' },
      { name: 'Wicomico', city: 'Salisbury' },
      { name: 'Worcester', city: 'Snow Hill' },
    ],
  },

  // ===========================================================================
  // NORTH CAROLINA
  // ===========================================================================
  'north-carolina': {
    slug: 'north-carolina',
    name: 'North Carolina',
    nameEs: 'Carolina del Norte',
    countyCount: 100,
    additionalContent: 'Carolina del Norte tiene una comunidad hispana grande y diversa, especialmente en Charlotte, Raleigh, Durham, y las áreas agrícolas del este del estado. Los tribunales de familia en los 100 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Carolina del Norte?',
        answer: 'Sí. En los 100 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Alamance', city: 'Graham' },
      { name: 'Alexander', city: 'Taylorsville' },
      { name: 'Alleghany', city: 'Sparta' },
      { name: 'Anson', city: 'Wadesboro' },
      { name: 'Ashe', city: 'Jefferson' },
      { name: 'Avery', city: 'Newland' },
      { name: 'Beaufort', city: 'Washington' },
      { name: 'Bertie', city: 'Windsor' },
      { name: 'Bladen', city: 'Elizabethtown' },
      { name: 'Brunswick', city: 'Bolivia' },
      { name: 'Buncombe', city: 'Asheville' },
      { name: 'Burke', city: 'Morganton' },
      { name: 'Cabarrus', city: 'Concord' },
      { name: 'Caldwell', city: 'Lenoir' },
      { name: 'Camden', city: 'Camden' },
      { name: 'Carteret', city: 'Beaufort' },
      { name: 'Caswell', city: 'Yanceyville' },
      { name: 'Catawba', city: 'Newton' },
      { name: 'Chatham', city: 'Pittsboro' },
      { name: 'Cherokee', city: 'Murphy' },
      { name: 'Chowan', city: 'Edenton' },
      { name: 'Clay', city: 'Hayesville' },
      { name: 'Cleveland', city: 'Shelby' },
      { name: 'Columbus', city: 'Whiteville' },
      { name: 'Craven', city: 'New Bern' },
      { name: 'Cumberland', city: 'Fayetteville' },
      { name: 'Currituck', city: 'Currituck' },
      { name: 'Dare', city: 'Manteo' },
      { name: 'Davidson', city: 'Lexington' },
      { name: 'Davie', city: 'Mocksville' },
      { name: 'Duplin', city: 'Kenansville' },
      { name: 'Durham', city: 'Durham' },
      { name: 'Edgecombe', city: 'Tarboro' },
      { name: 'Forsyth', city: 'Winston-Salem' },
      { name: 'Franklin', city: 'Louisburg' },
      { name: 'Gaston', city: 'Gastonia' },
      { name: 'Gates', city: 'Gatesville' },
      { name: 'Graham', city: 'Robbinsville' },
      { name: 'Granville', city: 'Oxford' },
      { name: 'Greene', city: 'Snow Hill' },
      { name: 'Guilford', city: 'Greensboro' },
      { name: 'Halifax', city: 'Halifax' },
      { name: 'Harnett', city: 'Lillington' },
      { name: 'Haywood', city: 'Waynesville' },
      { name: 'Henderson', city: 'Hendersonville' },
      { name: 'Hertford', city: 'Winton' },
      { name: 'Hoke', city: 'Raeford' },
      { name: 'Hyde', city: 'Swan Quarter' },
      { name: 'Iredell', city: 'Statesville' },
      { name: 'Jackson', city: 'Sylva' },
      { name: 'Johnston', city: 'Smithfield' },
      { name: 'Jones', city: 'Trenton' },
      { name: 'Lee', city: 'Sanford' },
      { name: 'Lenoir', city: 'Kinston' },
      { name: 'Lincoln', city: 'Lincolnton' },
      { name: 'Macon', city: 'Franklin' },
      { name: 'Madison', city: 'Marshall' },
      { name: 'Martin', city: 'Williamston' },
      { name: 'McDowell', city: 'Marion' },
      { name: 'Mecklenburg', city: 'Charlotte' },
      { name: 'Mitchell', city: 'Bakersville' },
      { name: 'Montgomery', city: 'Troy' },
      { name: 'Moore', city: 'Carthage' },
      { name: 'Nash', city: 'Nashville' },
      { name: 'New Hanover', city: 'Wilmington' },
      { name: 'Northampton', city: 'Jackson' },
      { name: 'Onslow', city: 'Jacksonville' },
      { name: 'Orange', city: 'Hillsborough' },
      { name: 'Pamlico', city: 'Bayboro' },
      { name: 'Pasquotank', city: 'Elizabeth City' },
      { name: 'Pender', city: 'Burgaw' },
      { name: 'Perquimans', city: 'Hertford' },
      { name: 'Person', city: 'Roxboro' },
      { name: 'Pitt', city: 'Greenville' },
      { name: 'Polk', city: 'Columbus' },
      { name: 'Randolph', city: 'Asheboro' },
      { name: 'Richmond', city: 'Rockingham' },
      { name: 'Robeson', city: 'Lumberton' },
      { name: 'Rockingham', city: 'Wentworth' },
      { name: 'Rowan', city: 'Salisbury' },
      { name: 'Rutherford', city: 'Rutherfordton' },
      { name: 'Sampson', city: 'Clinton' },
      { name: 'Scotland', city: 'Laurinburg' },
      { name: 'Stanly', city: 'Albemarle' },
      { name: 'Stokes', city: 'Danbury' },
      { name: 'Surry', city: 'Dobson' },
      { name: 'Swain', city: 'Bryson City' },
      { name: 'Transylvania', city: 'Brevard' },
      { name: 'Tyrrell', city: 'Columbia' },
      { name: 'Union', city: 'Monroe' },
      { name: 'Vance', city: 'Henderson' },
      { name: 'Wake', city: 'Raleigh' },
      { name: 'Warren', city: 'Warrenton' },
      { name: 'Washington', city: 'Plymouth' },
      { name: 'Watauga', city: 'Boone' },
      { name: 'Wayne', city: 'Goldsboro' },
      { name: 'Wilkes', city: 'Wilkesboro' },
      { name: 'Wilson', city: 'Wilson' },
      { name: 'Yadkin', city: 'Yadkinville' },
      { name: 'Yancey', city: 'Burnsville' },
    ],
  },

  // ===========================================================================
  // SOUTH CAROLINA
  // ===========================================================================
  'south-carolina': {
    slug: 'south-carolina',
    name: 'South Carolina',
    nameEs: 'Carolina del Sur',
    countyCount: 46,
    additionalContent: 'Carolina del Sur tiene una comunidad hispana en crecimiento, especialmente en Greenville, Columbia, Charleston, y Myrtle Beach. Los tribunales de familia en los 46 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Carolina del Sur?',
        answer: 'Sí. En los 46 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Abbeville', city: 'Abbeville' },
      { name: 'Aiken', city: 'Aiken' },
      { name: 'Allendale', city: 'Allendale' },
      { name: 'Anderson', city: 'Anderson' },
      { name: 'Bamberg', city: 'Bamberg' },
      { name: 'Barnwell', city: 'Barnwell' },
      { name: 'Beaufort', city: 'Beaufort' },
      { name: 'Berkeley', city: 'Moncks Corner' },
      { name: 'Calhoun', city: 'St. Matthews' },
      { name: 'Charleston', city: 'Charleston' },
      { name: 'Cherokee', city: 'Gaffney' },
      { name: 'Chester', city: 'Chester' },
      { name: 'Chesterfield', city: 'Chesterfield' },
      { name: 'Clarendon', city: 'Manning' },
      { name: 'Colleton', city: 'Walterboro' },
      { name: 'Darlington', city: 'Darlington' },
      { name: 'Dillon', city: 'Dillon' },
      { name: 'Dorchester', city: 'St. George' },
      { name: 'Edgefield', city: 'Edgefield' },
      { name: 'Fairfield', city: 'Winnsboro' },
      { name: 'Florence', city: 'Florence' },
      { name: 'Georgetown', city: 'Georgetown' },
      { name: 'Greenville', city: 'Greenville' },
      { name: 'Greenwood', city: 'Greenwood' },
      { name: 'Hampton', city: 'Hampton' },
      { name: 'Horry', city: 'Conway' },
      { name: 'Jasper', city: 'Ridgeland' },
      { name: 'Kershaw', city: 'Camden' },
      { name: 'Lancaster', city: 'Lancaster' },
      { name: 'Laurens', city: 'Laurens' },
      { name: 'Lee', city: 'Bishopville' },
      { name: 'Lexington', city: 'Lexington' },
      { name: 'Marion', city: 'Marion' },
      { name: 'Marlboro', city: 'Bennettsville' },
      { name: 'McCormick', city: 'McCormick' },
      { name: 'Newberry', city: 'Newberry' },
      { name: 'Oconee', city: 'Walhalla' },
      { name: 'Orangeburg', city: 'Orangeburg' },
      { name: 'Pickens', city: 'Pickens' },
      { name: 'Richland', city: 'Columbia' },
      { name: 'Saluda', city: 'Saluda' },
      { name: 'Spartanburg', city: 'Spartanburg' },
      { name: 'Sumter', city: 'Sumter' },
      { name: 'Union', city: 'Union' },
      { name: 'Williamsburg', city: 'Kingstree' },
      { name: 'York', city: 'York' },
    ],
  },

  // ===========================================================================
  // VIRGINIA
  // ===========================================================================
  'virginia': {
    slug: 'virginia',
    name: 'Virginia',
    nameEs: 'Virginia',
    countyCount: 133,
    additionalContent: 'Virginia tiene una comunidad hispana grande y diversa, especialmente en el área de Washington D.C., Richmond, y Virginia Beach. Los tribunales de familia en los 133 condados y ciudades independientes reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Virginia?',
        answer: 'Sí. En los 133 condados y ciudades. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Accomack', city: 'Accomac' },
      { name: 'Albemarle', city: 'Charlottesville' },
      { name: 'Alleghany', city: 'Covington' },
      { name: 'Amelia', city: 'Amelia Court House' },
      { name: 'Amherst', city: 'Amherst' },
      { name: 'Appomattox', city: 'Appomattox' },
      { name: 'Arlington', city: 'Arlington' },
      { name: 'Augusta', city: 'Staunton' },
      { name: 'Bath', city: 'Warm Springs' },
      { name: 'Bedford', city: 'Bedford' },
      { name: 'Bland', city: 'Bland' },
      { name: 'Botetourt', city: 'Fincastle' },
      { name: 'Brunswick', city: 'Lawrenceville' },
      { name: 'Buchanan', city: 'Grundy' },
      { name: 'Buckingham', city: 'Buckingham' },
      { name: 'Campbell', city: 'Rustburg' },
      { name: 'Caroline', city: 'Bowling Green' },
      { name: 'Carroll', city: 'Hillsville' },
      { name: 'Charles City', city: 'Charles City' },
      { name: 'Charlotte', city: 'Charlotte Court House' },
      { name: 'Chesterfield', city: 'Chesterfield' },
      { name: 'Clarke', city: 'Berryville' },
      { name: 'Craig', city: 'New Castle' },
      { name: 'Culpeper', city: 'Culpeper' },
      { name: 'Cumberland', city: 'Cumberland' },
      { name: 'Dickenson', city: 'Clintwood' },
      { name: 'Dinwiddie', city: 'Dinwiddie' },
      { name: 'Essex', city: 'Tappahannock' },
      { name: 'Fairfax County', city: 'Fairfax' },
      { name: 'Fauquier', city: 'Warrenton' },
      { name: 'Floyd', city: 'Floyd' },
      { name: 'Fluvanna', city: 'Palmyra' },
      { name: 'Franklin', city: 'Rocky Mount' },
      { name: 'Frederick', city: 'Winchester' },
      { name: 'Giles', city: 'Pearisburg' },
      { name: 'Gloucester', city: 'Gloucester' },
      { name: 'Goochland', city: 'Goochland' },
      { name: 'Grayson', city: 'Independence' },
      { name: 'Greene', city: 'Stanardsville' },
      { name: 'Greensville', city: 'Emporia' },
      { name: 'Halifax', city: 'Halifax' },
      { name: 'Hanover', city: 'Hanover' },
      { name: 'Henrico', city: 'Richmond' },
      { name: 'Henry', city: 'Martinsville' },
      { name: 'Highland', city: 'Monterey' },
      { name: 'Isle of Wight', city: 'Isle of Wight' },
      { name: 'James City', city: 'Williamsburg' },
      { name: 'King and Queen', city: 'King and Queen Court House' },
      { name: 'King George', city: 'King George' },
      { name: 'King William', city: 'King William' },
      { name: 'Lancaster', city: 'Lancaster' },
      { name: 'Lee', city: 'Jonesville' },
      { name: 'Loudoun', city: 'Leesburg' },
      { name: 'Louisa', city: 'Louisa' },
      { name: 'Lunenburg', city: 'Lunenburg' },
      { name: 'Madison', city: 'Madison' },
      { name: 'Mathews', city: 'Mathews' },
      { name: 'Mecklenburg', city: 'Boydton' },
      { name: 'Middlesex', city: 'Saluda' },
      { name: 'Montgomery', city: 'Christiansburg' },
      { name: 'Nelson', city: 'Lovingston' },
      { name: 'New Kent', city: 'New Kent' },
      { name: 'Northampton', city: 'Eastville' },
      { name: 'Northumberland', city: 'Heathsville' },
      { name: 'Nottoway', city: 'Nottoway' },
      { name: 'Orange', city: 'Orange' },
      { name: 'Page', city: 'Luray' },
      { name: 'Patrick', city: 'Stuart' },
      { name: 'Pittsylvania', city: 'Chatham' },
      { name: 'Powhatan', city: 'Powhatan' },
      { name: 'Prince Edward', city: 'Farmville' },
      { name: 'Prince George', city: 'Prince George' },
      { name: 'Prince William', city: 'Manassas' },
      { name: 'Pulaski', city: 'Pulaski' },
      { name: 'Rappahannock', city: 'Washington' },
      { name: 'Richmond County', city: 'Warsaw' },
      { name: 'Roanoke County', city: 'Salem' },
      { name: 'Rockbridge', city: 'Lexington' },
      { name: 'Rockingham', city: 'Harrisonburg' },
      { name: 'Russell', city: 'Lebanon' },
      { name: 'Scott', city: 'Gate City' },
      { name: 'Shenandoah', city: 'Woodstock' },
      { name: 'Smyth', city: 'Marion' },
      { name: 'Southampton', city: 'Courtland' },
      { name: 'Spotsylvania', city: 'Spotsylvania' },
      { name: 'Stafford', city: 'Stafford' },
      { name: 'Surry', city: 'Surry' },
      { name: 'Sussex', city: 'Sussex' },
      { name: 'Tazewell', city: 'Tazewell' },
      { name: 'Warren', city: 'Front Royal' },
      { name: 'Washington', city: 'Abingdon' },
      { name: 'Westmoreland', city: 'Montross' },
      { name: 'Wise', city: 'Wise' },
      { name: 'Wythe', city: 'Wytheville' },
      { name: 'York', city: 'Yorktown' },
      { name: 'Alexandria (city)', city: 'Alexandria' },
      { name: 'Bristol (city)', city: 'Bristol' },
      { name: 'Buena Vista (city)', city: 'Buena Vista' },
      { name: 'Charlottesville (city)', city: 'Charlottesville' },
      { name: 'Chesapeake (city)', city: 'Chesapeake' },
      { name: 'Colonial Heights (city)', city: 'Colonial Heights' },
      { name: 'Covington (city)', city: 'Covington' },
      { name: 'Danville (city)', city: 'Danville' },
      { name: 'Emporia (city)', city: 'Emporia' },
      { name: 'Fairfax (city)', city: 'Fairfax' },
      { name: 'Falls Church (city)', city: 'Falls Church' },
      { name: 'Franklin (city)', city: 'Franklin' },
      { name: 'Fredericksburg (city)', city: 'Fredericksburg' },
      { name: 'Galax (city)', city: 'Galax' },
      { name: 'Hampton (city)', city: 'Hampton' },
      { name: 'Harrisonburg (city)', city: 'Harrisonburg' },
      { name: 'Hopewell (city)', city: 'Hopewell' },
      { name: 'Lexington (city)', city: 'Lexington' },
      { name: 'Lynchburg (city)', city: 'Lynchburg' },
      { name: 'Manassas (city)', city: 'Manassas' },
      { name: 'Manassas Park (city)', city: 'Manassas Park' },
      { name: 'Martinsville (city)', city: 'Martinsville' },
      { name: 'Newport News (city)', city: 'Newport News' },
      { name: 'Norfolk (city)', city: 'Norfolk' },
      { name: 'Norton (city)', city: 'Norton' },
      { name: 'Petersburg (city)', city: 'Petersburg' },
      { name: 'Poquoson (city)', city: 'Poquoson' },
      { name: 'Portsmouth (city)', city: 'Portsmouth' },
      { name: 'Radford (city)', city: 'Radford' },
      { name: 'Richmond (city)', city: 'Richmond' },
      { name: 'Roanoke (city)', city: 'Roanoke' },
      { name: 'Salem (city)', city: 'Salem' },
      { name: 'Staunton (city)', city: 'Staunton' },
      { name: 'Suffolk (city)', city: 'Suffolk' },
      { name: 'Virginia Beach (city)', city: 'Virginia Beach' },
      { name: 'Waynesboro (city)', city: 'Waynesboro' },
      { name: 'Williamsburg (city)', city: 'Williamsburg' },
      { name: 'Winchester (city)', city: 'Winchester' },
    ],
  },

  // ===========================================================================
  // WEST VIRGINIA
  // ===========================================================================
  'west-virginia': {
    slug: 'west-virginia',
    name: 'West Virginia',
    nameEs: 'Virginia Occidental',
    countyCount: 55,
    additionalContent: 'Virginia Occidental tiene una comunidad hispana en crecimiento, especialmente en Charleston, Huntington, y Morgantown. Los tribunales de familia en los 55 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Virginia Occidental?',
        answer: 'Sí. En los 55 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Barbour', city: 'Philippi' },
      { name: 'Berkeley', city: 'Martinsburg' },
      { name: 'Boone', city: 'Madison' },
      { name: 'Braxton', city: 'Sutton' },
      { name: 'Brooke', city: 'Wellsburg' },
      { name: 'Cabell', city: 'Huntington' },
      { name: 'Calhoun', city: 'Grantsville' },
      { name: 'Clay', city: 'Clay' },
      { name: 'Doddridge', city: 'West Union' },
      { name: 'Fayette', city: 'Fayetteville' },
      { name: 'Gilmer', city: 'Glenville' },
      { name: 'Grant', city: 'Petersburg' },
      { name: 'Greenbrier', city: 'Lewisburg' },
      { name: 'Hampshire', city: 'Romney' },
      { name: 'Hancock', city: 'New Cumberland' },
      { name: 'Hardy', city: 'Moorefield' },
      { name: 'Harrison', city: 'Clarksburg' },
      { name: 'Jackson', city: 'Ripley' },
      { name: 'Jefferson', city: 'Charles Town' },
      { name: 'Kanawha', city: 'Charleston' },
      { name: 'Lewis', city: 'Weston' },
      { name: 'Lincoln', city: 'Hamlin' },
      { name: 'Logan', city: 'Logan' },
      { name: 'Marion', city: 'Fairmont' },
      { name: 'Marshall', city: 'Moundsville' },
      { name: 'Mason', city: 'Point Pleasant' },
      { name: 'McDowell', city: 'Welch' },
      { name: 'Mercer', city: 'Princeton' },
      { name: 'Mineral', city: 'Keyser' },
      { name: 'Mingo', city: 'Williamson' },
      { name: 'Monongalia', city: 'Morgantown' },
      { name: 'Monroe', city: 'Union' },
      { name: 'Morgan', city: 'Berkeley Springs' },
      { name: 'Nicholas', city: 'Summersville' },
      { name: 'Ohio', city: 'Wheeling' },
      { name: 'Pendleton', city: 'Franklin' },
      { name: 'Pleasants', city: 'St. Marys' },
      { name: 'Pocahontas', city: 'Marlinton' },
      { name: 'Preston', city: 'Kingwood' },
      { name: 'Putnam', city: 'Winfield' },
      { name: 'Raleigh', city: 'Beckley' },
      { name: 'Randolph', city: 'Elkins' },
      { name: 'Ritchie', city: 'Harrisville' },
      { name: 'Roane', city: 'Spencer' },
      { name: 'Summers', city: 'Hinton' },
      { name: 'Taylor', city: 'Grafton' },
      { name: 'Tucker', city: 'Parsons' },
      { name: 'Tyler', city: 'Middlebourne' },
      { name: 'Upshur', city: 'Buckhannon' },
      { name: 'Wayne', city: 'Wayne' },
      { name: 'Webster', city: 'Webster Springs' },
      { name: 'Wetzel', city: 'New Martinsville' },
      { name: 'Wirt', city: 'Elizabeth' },
      { name: 'Wood', city: 'Parkersburg' },
      { name: 'Wyoming', city: 'Pineville' },
    ],
  },
};
