/**
 * South Central Region
 * States: Alabama, Arkansas, Kentucky, Louisiana, Mississippi, Oklahoma, Tennessee
 * 7 states, ~580 counties
 */

import type { StateData } from './types';

export const southCentralStates: Record<string, StateData> = {
  // ===========================================================================
  // ALABAMA
  // ===========================================================================
  'alabama': {
    slug: 'alabama',
    name: 'Alabama',
    nameEs: 'Alabama',
    countyCount: 67,
    additionalContent: 'Alabama tiene una comunidad hispana en crecimiento, especialmente en Birmingham, Huntsville, y Mobile. Los tribunales de familia en los 67 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Alabama?',
        answer: 'Sí. En los 67 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Autauga', city: 'Prattville' },
      { name: 'Baldwin', city: 'Bay Minette' },
      { name: 'Barbour', city: 'Clayton' },
      { name: 'Bibb', city: 'Centreville' },
      { name: 'Blount', city: 'Oneonta' },
      { name: 'Bullock', city: 'Union Springs' },
      { name: 'Butler', city: 'Greenville' },
      { name: 'Calhoun', city: 'Anniston' },
      { name: 'Chambers', city: 'LaFayette' },
      { name: 'Cherokee', city: 'Centre' },
      { name: 'Chilton', city: 'Clanton' },
      { name: 'Choctaw', city: 'Butler' },
      { name: 'Clarke', city: 'Grove Hill' },
      { name: 'Clay', city: 'Ashland' },
      { name: 'Cleburne', city: 'Heflin' },
      { name: 'Coffee', city: 'Elba' },
      { name: 'Colbert', city: 'Tuscumbia' },
      { name: 'Conecuh', city: 'Evergreen' },
      { name: 'Coosa', city: 'Rockford' },
      { name: 'Covington', city: 'Andalusia' },
      { name: 'Crenshaw', city: 'Luverne' },
      { name: 'Cullman', city: 'Cullman' },
      { name: 'Dale', city: 'Ozark' },
      { name: 'Dallas', city: 'Selma' },
      { name: 'DeKalb', city: 'Fort Payne' },
      { name: 'Elmore', city: 'Wetumpka' },
      { name: 'Escambia', city: 'Brewton' },
      { name: 'Etowah', city: 'Gadsden' },
      { name: 'Fayette', city: 'Fayette' },
      { name: 'Franklin', city: 'Russellville' },
      { name: 'Geneva', city: 'Geneva' },
      { name: 'Greene', city: 'Eutaw' },
      { name: 'Hale', city: 'Greensboro' },
      { name: 'Henry', city: 'Abbeville' },
      { name: 'Houston', city: 'Dothan' },
      { name: 'Jackson', city: 'Scottsboro' },
      { name: 'Jefferson', city: 'Birmingham' },
      { name: 'Lamar', city: 'Vernon' },
      { name: 'Lauderdale', city: 'Florence' },
      { name: 'Lawrence', city: 'Moulton' },
      { name: 'Lee', city: 'Opelika' },
      { name: 'Limestone', city: 'Athens' },
      { name: 'Lowndes', city: 'Hayneville' },
      { name: 'Macon', city: 'Tuskegee' },
      { name: 'Madison', city: 'Huntsville' },
      { name: 'Marengo', city: 'Linden' },
      { name: 'Marion', city: 'Hamilton' },
      { name: 'Marshall', city: 'Guntersville' },
      { name: 'Mobile', city: 'Mobile' },
      { name: 'Monroe', city: 'Monroeville' },
      { name: 'Montgomery', city: 'Montgomery' },
      { name: 'Morgan', city: 'Decatur' },
      { name: 'Perry', city: 'Marion' },
      { name: 'Pickens', city: 'Carrollton' },
      { name: 'Pike', city: 'Troy' },
      { name: 'Randolph', city: 'Wedowee' },
      { name: 'Russell', city: 'Phenix City' },
      { name: 'Shelby', city: 'Columbiana' },
      { name: 'St. Clair', city: 'Ashville' },
      { name: 'Sumter', city: 'Livingston' },
      { name: 'Talladega', city: 'Talladega' },
      { name: 'Tallapoosa', city: 'Dadeville' },
      { name: 'Tuscaloosa', city: 'Tuscaloosa' },
      { name: 'Walker', city: 'Jasper' },
      { name: 'Washington', city: 'Chatom' },
      { name: 'Wilcox', city: 'Camden' },
      { name: 'Winston', city: 'Double Springs' },
    ],
  },

  // ===========================================================================
  // ARKANSAS
  // ===========================================================================
  'arkansas': {
    slug: 'arkansas',
    name: 'Arkansas',
    nameEs: 'Arkansas',
    countyCount: 75,
    additionalContent: 'Arkansas tiene una comunidad hispana en crecimiento, especialmente en Little Rock, Springdale, Rogers, y Fort Smith. Los tribunales de familia en los 75 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Arkansas?',
        answer: 'Sí. En los 75 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Arkansas', city: 'DeWitt' },
      { name: 'Ashley', city: 'Hamburg' },
      { name: 'Baxter', city: 'Mountain Home' },
      { name: 'Benton', city: 'Bentonville' },
      { name: 'Boone', city: 'Harrison' },
      { name: 'Bradley', city: 'Warren' },
      { name: 'Calhoun', city: 'Hampton' },
      { name: 'Carroll', city: 'Berryville' },
      { name: 'Chicot', city: 'Lake Village' },
      { name: 'Clark', city: 'Arkadelphia' },
      { name: 'Clay', city: 'Piggott' },
      { name: 'Cleburne', city: 'Heber Springs' },
      { name: 'Cleveland', city: 'Rison' },
      { name: 'Columbia', city: 'Magnolia' },
      { name: 'Conway', city: 'Morrilton' },
      { name: 'Craighead', city: 'Jonesboro' },
      { name: 'Crawford', city: 'Van Buren' },
      { name: 'Crittenden', city: 'Marion' },
      { name: 'Cross', city: 'Wynne' },
      { name: 'Dallas', city: 'Fordyce' },
      { name: 'Desha', city: 'Arkansas City' },
      { name: 'Drew', city: 'Monticello' },
      { name: 'Faulkner', city: 'Conway' },
      { name: 'Franklin', city: 'Ozark' },
      { name: 'Fulton', city: 'Salem' },
      { name: 'Garland', city: 'Hot Springs' },
      { name: 'Grant', city: 'Sheridan' },
      { name: 'Greene', city: 'Paragould' },
      { name: 'Hempstead', city: 'Hope' },
      { name: 'Hot Spring', city: 'Malvern' },
      { name: 'Howard', city: 'Nashville' },
      { name: 'Independence', city: 'Batesville' },
      { name: 'Izard', city: 'Melbourne' },
      { name: 'Jackson', city: 'Newport' },
      { name: 'Jefferson', city: 'Pine Bluff' },
      { name: 'Johnson', city: 'Clarksville' },
      { name: 'Lafayette', city: 'Lewisville' },
      { name: 'Lawrence', city: 'Walnut Ridge' },
      { name: 'Lee', city: 'Marianna' },
      { name: 'Lincoln', city: 'Star City' },
      { name: 'Little River', city: 'Ashdown' },
      { name: 'Logan', city: 'Paris' },
      { name: 'Lonoke', city: 'Lonoke' },
      { name: 'Madison', city: 'Huntsville' },
      { name: 'Marion', city: 'Yellville' },
      { name: 'Miller', city: 'Texarkana' },
      { name: 'Mississippi', city: 'Blytheville' },
      { name: 'Monroe', city: 'Clarendon' },
      { name: 'Montgomery', city: 'Mount Ida' },
      { name: 'Nevada', city: 'Prescott' },
      { name: 'Newton', city: 'Jasper' },
      { name: 'Ouachita', city: 'Camden' },
      { name: 'Perry', city: 'Perryville' },
      { name: 'Phillips', city: 'Helena-West Helena' },
      { name: 'Pike', city: 'Murfreesboro' },
      { name: 'Poinsett', city: 'Harrisburg' },
      { name: 'Polk', city: 'Mena' },
      { name: 'Pope', city: 'Russellville' },
      { name: 'Prairie', city: 'Des Arc' },
      { name: 'Pulaski', city: 'Little Rock' },
      { name: 'Randolph', city: 'Pocahontas' },
      { name: 'Saline', city: 'Benton' },
      { name: 'Scott', city: 'Waldron' },
      { name: 'Searcy', city: 'Marshall' },
      { name: 'Sebastian', city: 'Fort Smith' },
      { name: 'Sevier', city: 'De Queen' },
      { name: 'Sharp', city: 'Ash Flat' },
      { name: 'St. Francis', city: 'Forrest City' },
      { name: 'Stone', city: 'Mountain View' },
      { name: 'Union', city: 'El Dorado' },
      { name: 'Van Buren', city: 'Clinton' },
      { name: 'Washington', city: 'Fayetteville' },
      { name: 'White', city: 'Searcy' },
      { name: 'Woodruff', city: 'Augusta' },
      { name: 'Yell', city: 'Danville' },
    ],
  },

  // ===========================================================================
  // KENTUCKY
  // ===========================================================================
  'kentucky': {
    slug: 'kentucky',
    name: 'Kentucky',
    nameEs: 'Kentucky',
    countyCount: 120,
    additionalContent: 'Kentucky tiene una comunidad hispana en crecimiento, especialmente en Louisville, Lexington, y Bowling Green. Los tribunales de familia en los 120 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Kentucky?',
        answer: 'Sí. En los 120 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adair', city: 'Columbia' },
      { name: 'Allen', city: 'Scottsville' },
      { name: 'Anderson', city: 'Lawrenceburg' },
      { name: 'Ballard', city: 'Wickliffe' },
      { name: 'Barren', city: 'Glasgow' },
      { name: 'Bath', city: 'Owingsville' },
      { name: 'Bell', city: 'Pineville' },
      { name: 'Boone', city: 'Burlington' },
      { name: 'Bourbon', city: 'Paris' },
      { name: 'Boyd', city: 'Catlettsburg' },
      { name: 'Boyle', city: 'Danville' },
      { name: 'Bracken', city: 'Brooksville' },
      { name: 'Breathitt', city: 'Jackson' },
      { name: 'Breckinridge', city: 'Hardinsburg' },
      { name: 'Bullitt', city: 'Shepherdsville' },
      { name: 'Butler', city: 'Morgantown' },
      { name: 'Caldwell', city: 'Princeton' },
      { name: 'Calloway', city: 'Murray' },
      { name: 'Campbell', city: 'Alexandria' },
      { name: 'Carlisle', city: 'Bardwell' },
      { name: 'Carroll', city: 'Carrollton' },
      { name: 'Carter', city: 'Grayson' },
      { name: 'Casey', city: 'Liberty' },
      { name: 'Christian', city: 'Hopkinsville' },
      { name: 'Clark', city: 'Winchester' },
      { name: 'Clay', city: 'Manchester' },
      { name: 'Clinton', city: 'Albany' },
      { name: 'Crittenden', city: 'Marion' },
      { name: 'Cumberland', city: 'Burkesville' },
      { name: 'Daviess', city: 'Owensboro' },
      { name: 'Edmonson', city: 'Brownsville' },
      { name: 'Elliott', city: 'Sandy Hook' },
      { name: 'Estill', city: 'Irvine' },
      { name: 'Fayette', city: 'Lexington' },
      { name: 'Fleming', city: 'Flemingsburg' },
      { name: 'Floyd', city: 'Prestonsburg' },
      { name: 'Franklin', city: 'Frankfort' },
      { name: 'Fulton', city: 'Hickman' },
      { name: 'Gallatin', city: 'Warsaw' },
      { name: 'Garrard', city: 'Lancaster' },
      { name: 'Grant', city: 'Williamstown' },
      { name: 'Graves', city: 'Mayfield' },
      { name: 'Grayson', city: 'Leitchfield' },
      { name: 'Green', city: 'Greensburg' },
      { name: 'Greenup', city: 'Greenup' },
      { name: 'Hancock', city: 'Hawesville' },
      { name: 'Hardin', city: 'Elizabethtown' },
      { name: 'Harlan', city: 'Harlan' },
      { name: 'Harrison', city: 'Cynthiana' },
      { name: 'Hart', city: 'Munfordville' },
      { name: 'Henderson', city: 'Henderson' },
      { name: 'Henry', city: 'New Castle' },
      { name: 'Hickman', city: 'Clinton' },
      { name: 'Hopkins', city: 'Madisonville' },
      { name: 'Jackson', city: 'McKee' },
      { name: 'Jefferson', city: 'Louisville' },
      { name: 'Jessamine', city: 'Nicholasville' },
      { name: 'Johnson', city: 'Paintsville' },
      { name: 'Kenton', city: 'Covington' },
      { name: 'Knott', city: 'Hindman' },
      { name: 'Knox', city: 'Barbourville' },
      { name: 'Larue', city: 'Hodgenville' },
      { name: 'Laurel', city: 'London' },
      { name: 'Lawrence', city: 'Louisa' },
      { name: 'Lee', city: 'Beattyville' },
      { name: 'Leslie', city: 'Hyden' },
      { name: 'Letcher', city: 'Whitesburg' },
      { name: 'Lewis', city: 'Vanceburg' },
      { name: 'Lincoln', city: 'Stanford' },
      { name: 'Livingston', city: 'Smithland' },
      { name: 'Logan', city: 'Russellville' },
      { name: 'Lyon', city: 'Eddyville' },
      { name: 'Madison', city: 'Richmond' },
      { name: 'Magoffin', city: 'Salyersville' },
      { name: 'Marion', city: 'Lebanon' },
      { name: 'Marshall', city: 'Benton' },
      { name: 'Martin', city: 'Inez' },
      { name: 'Mason', city: 'Maysville' },
      { name: 'McCracken', city: 'Paducah' },
      { name: 'McCreary', city: 'Whitley City' },
      { name: 'McLean', city: 'Calhoun' },
      { name: 'Meade', city: 'Brandenburg' },
      { name: 'Menifee', city: 'Frenchburg' },
      { name: 'Mercer', city: 'Harrodsburg' },
      { name: 'Metcalfe', city: 'Edmonton' },
      { name: 'Monroe', city: 'Tompkinsville' },
      { name: 'Montgomery', city: 'Mount Sterling' },
      { name: 'Morgan', city: 'West Liberty' },
      { name: 'Muhlenberg', city: 'Greenville' },
      { name: 'Nelson', city: 'Bardstown' },
      { name: 'Nicholas', city: 'Carlisle' },
      { name: 'Ohio', city: 'Hartford' },
      { name: 'Oldham', city: 'La Grange' },
      { name: 'Owen', city: 'Owenton' },
      { name: 'Owsley', city: 'Booneville' },
      { name: 'Pendleton', city: 'Falmouth' },
      { name: 'Perry', city: 'Hazard' },
      { name: 'Pike', city: 'Pikeville' },
      { name: 'Powell', city: 'Stanton' },
      { name: 'Pulaski', city: 'Somerset' },
      { name: 'Robertson', city: 'Mount Olivet' },
      { name: 'Rockcastle', city: 'Mount Vernon' },
      { name: 'Rowan', city: 'Morehead' },
      { name: 'Russell', city: 'Jamestown' },
      { name: 'Scott', city: 'Georgetown' },
      { name: 'Shelby', city: 'Shelbyville' },
      { name: 'Simpson', city: 'Franklin' },
      { name: 'Spencer', city: 'Taylorsville' },
      { name: 'Taylor', city: 'Campbellsville' },
      { name: 'Todd', city: 'Elkton' },
      { name: 'Trigg', city: 'Cadiz' },
      { name: 'Trimble', city: 'Bedford' },
      { name: 'Union', city: 'Morganfield' },
      { name: 'Warren', city: 'Bowling Green' },
      { name: 'Washington', city: 'Springfield' },
      { name: 'Wayne', city: 'Monticello' },
      { name: 'Webster', city: 'Dixon' },
      { name: 'Whitley', city: 'Williamsburg' },
      { name: 'Wolfe', city: 'Campton' },
      { name: 'Woodford', city: 'Versailles' },
    ],
  },

  // ===========================================================================
  // LOUISIANA
  // ===========================================================================
  'louisiana': {
    slug: 'louisiana',
    name: 'Louisiana',
    nameEs: 'Luisiana',
    countyCount: 64,
    additionalContent: 'Luisiana tiene una comunidad hispana vibrante, especialmente en Nueva Orleans, Baton Rouge, y las parroquias del sur del estado. Los tribunales de familia en las 64 parroquias reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Luisiana?',
        answer: 'Sí. En las 64 parroquias. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Acadia Parish', city: 'Crowley' },
      { name: 'Allen Parish', city: 'Oberlin' },
      { name: 'Ascension Parish', city: 'Donaldsonville' },
      { name: 'Assumption Parish', city: 'Napoleonville' },
      { name: 'Avoyelles Parish', city: 'Marksville' },
      { name: 'Beauregard Parish', city: 'DeRidder' },
      { name: 'Bienville Parish', city: 'Arcadia' },
      { name: 'Bossier Parish', city: 'Benton' },
      { name: 'Caddo Parish', city: 'Shreveport' },
      { name: 'Calcasieu Parish', city: 'Lake Charles' },
      { name: 'Caldwell Parish', city: 'Columbia' },
      { name: 'Cameron Parish', city: 'Cameron' },
      { name: 'Catahoula Parish', city: 'Harrisonburg' },
      { name: 'Claiborne Parish', city: 'Homer' },
      { name: 'Concordia Parish', city: 'Vidalia' },
      { name: 'De Soto Parish', city: 'Mansfield' },
      { name: 'East Baton Rouge Parish', city: 'Baton Rouge' },
      { name: 'East Carroll Parish', city: 'Lake Providence' },
      { name: 'East Feliciana Parish', city: 'Clinton' },
      { name: 'Evangeline Parish', city: 'Ville Platte' },
      { name: 'Franklin Parish', city: 'Winnsboro' },
      { name: 'Grant Parish', city: 'Colfax' },
      { name: 'Iberia Parish', city: 'New Iberia' },
      { name: 'Iberville Parish', city: 'Plaquemine' },
      { name: 'Jackson Parish', city: 'Jonesboro' },
      { name: 'Jefferson Parish', city: 'Gretna' },
      { name: 'Jefferson Davis Parish', city: 'Jennings' },
      { name: 'Lafayette Parish', city: 'Lafayette' },
      { name: 'Lafourche Parish', city: 'Thibodaux' },
      { name: 'LaSalle Parish', city: 'Jena' },
      { name: 'Lincoln Parish', city: 'Ruston' },
      { name: 'Livingston Parish', city: 'Livingston' },
      { name: 'Madison Parish', city: 'Tallulah' },
      { name: 'Morehouse Parish', city: 'Bastrop' },
      { name: 'Natchitoches Parish', city: 'Natchitoches' },
      { name: 'Orleans Parish', city: 'New Orleans' },
      { name: 'Ouachita Parish', city: 'Monroe' },
      { name: 'Plaquemines Parish', city: 'Pointe a la Hache' },
      { name: 'Pointe Coupee Parish', city: 'New Roads' },
      { name: 'Rapides Parish', city: 'Alexandria' },
      { name: 'Red River Parish', city: 'Coushatta' },
      { name: 'Richland Parish', city: 'Rayville' },
      { name: 'Sabine Parish', city: 'Many' },
      { name: 'St. Bernard Parish', city: 'Chalmette' },
      { name: 'St. Charles Parish', city: 'Hahnville' },
      { name: 'St. Helena Parish', city: 'Greensburg' },
      { name: 'St. James Parish', city: 'Convent' },
      { name: 'St. John the Baptist Parish', city: 'Edgard' },
      { name: 'St. Landry Parish', city: 'Opelousas' },
      { name: 'St. Martin Parish', city: 'St. Martinville' },
      { name: 'St. Mary Parish', city: 'Franklin' },
      { name: 'St. Tammany Parish', city: 'Covington' },
      { name: 'Tangipahoa Parish', city: 'Amite City' },
      { name: 'Tensas Parish', city: 'St. Joseph' },
      { name: 'Terrebonne Parish', city: 'Houma' },
      { name: 'Union Parish', city: 'Farmerville' },
      { name: 'Vermilion Parish', city: 'Abbeville' },
      { name: 'Vernon Parish', city: 'Leesville' },
      { name: 'Washington Parish', city: 'Franklinton' },
      { name: 'Webster Parish', city: 'Minden' },
      { name: 'West Baton Rouge Parish', city: 'Port Allen' },
      { name: 'West Carroll Parish', city: 'Oak Grove' },
      { name: 'West Feliciana Parish', city: 'St. Francisville' },
      { name: 'Winn Parish', city: 'Winnfield' },
    ],
  },

  // ===========================================================================
  // MISSISSIPPI
  // ===========================================================================
  'mississippi': {
    slug: 'mississippi',
    name: 'Mississippi',
    nameEs: 'Misisipi',
    countyCount: 82,
    additionalContent: 'Misisipi tiene una comunidad hispana en crecimiento, especialmente en Jackson, Gulfport, y las áreas agrícolas del Delta. Los tribunales de familia en los 82 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Misisipi?',
        answer: 'Sí. En los 82 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Natchez' },
      { name: 'Alcorn', city: 'Corinth' },
      { name: 'Amite', city: 'Liberty' },
      { name: 'Attala', city: 'Kosciusko' },
      { name: 'Benton', city: 'Ashland' },
      { name: 'Bolivar', city: 'Cleveland' },
      { name: 'Calhoun', city: 'Pittsboro' },
      { name: 'Carroll', city: 'Carrollton' },
      { name: 'Chickasaw', city: 'Houston' },
      { name: 'Choctaw', city: 'Ackerman' },
      { name: 'Claiborne', city: 'Port Gibson' },
      { name: 'Clarke', city: 'Quitman' },
      { name: 'Clay', city: 'West Point' },
      { name: 'Coahoma', city: 'Clarksdale' },
      { name: 'Copiah', city: 'Hazlehurst' },
      { name: 'Covington', city: 'Collins' },
      { name: 'DeSoto', city: 'Hernando' },
      { name: 'Forrest', city: 'Hattiesburg' },
      { name: 'Franklin', city: 'Meadville' },
      { name: 'George', city: 'Lucedale' },
      { name: 'Greene', city: 'Leakesville' },
      { name: 'Grenada', city: 'Grenada' },
      { name: 'Hancock', city: 'Bay St. Louis' },
      { name: 'Harrison', city: 'Gulfport' },
      { name: 'Hinds', city: 'Jackson' },
      { name: 'Holmes', city: 'Lexington' },
      { name: 'Humphreys', city: 'Belzoni' },
      { name: 'Issaquena', city: 'Mayersville' },
      { name: 'Itawamba', city: 'Fulton' },
      { name: 'Jackson', city: 'Pascagoula' },
      { name: 'Jasper', city: 'Bay Springs' },
      { name: 'Jefferson', city: 'Fayette' },
      { name: 'Jefferson Davis', city: 'Prentiss' },
      { name: 'Jones', city: 'Ellisville' },
      { name: 'Kemper', city: 'DeKalb' },
      { name: 'Lafayette', city: 'Oxford' },
      { name: 'Lamar', city: 'Purvis' },
      { name: 'Lauderdale', city: 'Meridian' },
      { name: 'Lawrence', city: 'Monticello' },
      { name: 'Leake', city: 'Carthage' },
      { name: 'Lee', city: 'Tupelo' },
      { name: 'Leflore', city: 'Greenwood' },
      { name: 'Lincoln', city: 'Brookhaven' },
      { name: 'Lowndes', city: 'Columbus' },
      { name: 'Madison', city: 'Canton' },
      { name: 'Marion', city: 'Columbia' },
      { name: 'Marshall', city: 'Holly Springs' },
      { name: 'Monroe', city: 'Aberdeen' },
      { name: 'Montgomery', city: 'Winona' },
      { name: 'Neshoba', city: 'Philadelphia' },
      { name: 'Newton', city: 'Decatur' },
      { name: 'Noxubee', city: 'Macon' },
      { name: 'Oktibbeha', city: 'Starkville' },
      { name: 'Panola', city: 'Batesville' },
      { name: 'Pearl River', city: 'Poplarville' },
      { name: 'Perry', city: 'New Augusta' },
      { name: 'Pike', city: 'Magnolia' },
      { name: 'Pontotoc', city: 'Pontotoc' },
      { name: 'Prentiss', city: 'Booneville' },
      { name: 'Quitman', city: 'Marks' },
      { name: 'Rankin', city: 'Brandon' },
      { name: 'Scott', city: 'Forest' },
      { name: 'Sharkey', city: 'Rolling Fork' },
      { name: 'Simpson', city: 'Mendenhall' },
      { name: 'Smith', city: 'Raleigh' },
      { name: 'Stone', city: 'Wiggins' },
      { name: 'Sunflower', city: 'Indianola' },
      { name: 'Tallahatchie', city: 'Charleston' },
      { name: 'Tate', city: 'Senatobia' },
      { name: 'Tippah', city: 'Ripley' },
      { name: 'Tishomingo', city: 'Iuka' },
      { name: 'Tunica', city: 'Tunica' },
      { name: 'Union', city: 'New Albany' },
      { name: 'Walthall', city: 'Tylertown' },
      { name: 'Warren', city: 'Vicksburg' },
      { name: 'Washington', city: 'Greenville' },
      { name: 'Wayne', city: 'Waynesboro' },
      { name: 'Webster', city: 'Walthall' },
      { name: 'Wilkinson', city: 'Woodville' },
      { name: 'Winston', city: 'Louisville' },
      { name: 'Yalobusha', city: 'Water Valley' },
      { name: 'Yazoo', city: 'Yazoo City' },
    ],
  },

  // ===========================================================================
  // OKLAHOMA
  // ===========================================================================
  'oklahoma': {
    slug: 'oklahoma',
    name: 'Oklahoma',
    nameEs: 'Oklahoma',
    countyCount: 77,
    additionalContent: 'Oklahoma tiene una comunidad hispana significativa, especialmente en Oklahoma City, Tulsa, y las áreas del sur del estado. Los tribunales de familia en los 77 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Oklahoma?',
        answer: 'Sí. En los 77 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adair', city: 'Stilwell' },
      { name: 'Alfalfa', city: 'Cherokee' },
      { name: 'Atoka', city: 'Atoka' },
      { name: 'Beaver', city: 'Beaver' },
      { name: 'Beckham', city: 'Sayre' },
      { name: 'Blaine', city: 'Watonga' },
      { name: 'Bryan', city: 'Durant' },
      { name: 'Caddo', city: 'Anadarko' },
      { name: 'Canadian', city: 'El Reno' },
      { name: 'Carter', city: 'Ardmore' },
      { name: 'Cherokee', city: 'Tahlequah' },
      { name: 'Choctaw', city: 'Hugo' },
      { name: 'Cimarron', city: 'Boise City' },
      { name: 'Cleveland', city: 'Norman' },
      { name: 'Coal', city: 'Coalgate' },
      { name: 'Comanche', city: 'Lawton' },
      { name: 'Cotton', city: 'Walters' },
      { name: 'Craig', city: 'Vinita' },
      { name: 'Creek', city: 'Sapulpa' },
      { name: 'Custer', city: 'Arapaho' },
      { name: 'Delaware', city: 'Jay' },
      { name: 'Dewey', city: 'Taloga' },
      { name: 'Ellis', city: 'Arnett' },
      { name: 'Garfield', city: 'Enid' },
      { name: 'Garvin', city: 'Pauls Valley' },
      { name: 'Grady', city: 'Chickasha' },
      { name: 'Grant', city: 'Medford' },
      { name: 'Greer', city: 'Mangum' },
      { name: 'Harmon', city: 'Hollis' },
      { name: 'Harper', city: 'Buffalo' },
      { name: 'Haskell', city: 'Stigler' },
      { name: 'Hughes', city: 'Holdenville' },
      { name: 'Jackson', city: 'Altus' },
      { name: 'Jefferson', city: 'Waurika' },
      { name: 'Johnston', city: 'Tishomingo' },
      { name: 'Kay', city: 'Newkirk' },
      { name: 'Kingfisher', city: 'Kingfisher' },
      { name: 'Kiowa', city: 'Hobart' },
      { name: 'Latimer', city: 'Wilburton' },
      { name: 'Le Flore', city: 'Poteau' },
      { name: 'Lincoln', city: 'Chandler' },
      { name: 'Logan', city: 'Guthrie' },
      { name: 'Love', city: 'Marietta' },
      { name: 'Major', city: 'Fairview' },
      { name: 'Marshall', city: 'Madill' },
      { name: 'Mayes', city: 'Pryor Creek' },
      { name: 'McClain', city: 'Purcell' },
      { name: 'McCurtain', city: 'Idabel' },
      { name: 'McIntosh', city: 'Eufaula' },
      { name: 'Murray', city: 'Sulphur' },
      { name: 'Muskogee', city: 'Muskogee' },
      { name: 'Noble', city: 'Perry' },
      { name: 'Nowata', city: 'Nowata' },
      { name: 'Okfuskee', city: 'Okemah' },
      { name: 'Oklahoma', city: 'Oklahoma City' },
      { name: 'Okmulgee', city: 'Okmulgee' },
      { name: 'Osage', city: 'Pawhuska' },
      { name: 'Ottawa', city: 'Miami' },
      { name: 'Pawnee', city: 'Pawnee' },
      { name: 'Payne', city: 'Stillwater' },
      { name: 'Pittsburg', city: 'McAlester' },
      { name: 'Pontotoc', city: 'Ada' },
      { name: 'Pottawatomie', city: 'Shawnee' },
      { name: 'Pushmataha', city: 'Antlers' },
      { name: 'Roger Mills', city: 'Cheyenne' },
      { name: 'Rogers', city: 'Claremore' },
      { name: 'Seminole', city: 'Wewoka' },
      { name: 'Sequoyah', city: 'Sallisaw' },
      { name: 'Stephens', city: 'Duncan' },
      { name: 'Texas', city: 'Guymon' },
      { name: 'Tillman', city: 'Frederick' },
      { name: 'Tulsa', city: 'Tulsa' },
      { name: 'Wagoner', city: 'Wagoner' },
      { name: 'Washington', city: 'Bartlesville' },
      { name: 'Washita', city: 'Cordell' },
      { name: 'Woods', city: 'Alva' },
      { name: 'Woodward', city: 'Woodward' },
    ],
  },

  // ===========================================================================
  // TENNESSEE
  // ===========================================================================
  'tennessee': {
    slug: 'tennessee',
    name: 'Tennessee',
    nameEs: 'Tennessee',
    countyCount: 95,
    additionalContent: 'Tennessee tiene una comunidad hispana en crecimiento, especialmente en Nashville, Memphis, Chattanooga, y Knoxville. Los tribunales de familia en los 95 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Tennessee?',
        answer: 'Sí. En los 95 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Anderson', city: 'Clinton' },
      { name: 'Bedford', city: 'Shelbyville' },
      { name: 'Benton', city: 'Camden' },
      { name: 'Bledsoe', city: 'Pikeville' },
      { name: 'Blount', city: 'Maryville' },
      { name: 'Bradley', city: 'Cleveland' },
      { name: 'Campbell', city: 'Jacksboro' },
      { name: 'Cannon', city: 'Woodbury' },
      { name: 'Carroll', city: 'Huntingdon' },
      { name: 'Carter', city: 'Elizabethton' },
      { name: 'Cheatham', city: 'Ashland City' },
      { name: 'Chester', city: 'Henderson' },
      { name: 'Claiborne', city: 'Tazewell' },
      { name: 'Clay', city: 'Celina' },
      { name: 'Cocke', city: 'Newport' },
      { name: 'Coffee', city: 'Manchester' },
      { name: 'Crockett', city: 'Alamo' },
      { name: 'Cumberland', city: 'Crossville' },
      { name: 'Davidson', city: 'Nashville' },
      { name: 'Decatur', city: 'Decaturville' },
      { name: 'DeKalb', city: 'Smithville' },
      { name: 'Dickson', city: 'Charlotte' },
      { name: 'Dyer', city: 'Dyersburg' },
      { name: 'Fayette', city: 'Somerville' },
      { name: 'Fentress', city: 'Jamestown' },
      { name: 'Franklin', city: 'Winchester' },
      { name: 'Gibson', city: 'Trenton' },
      { name: 'Giles', city: 'Pulaski' },
      { name: 'Grainger', city: 'Rutledge' },
      { name: 'Greene', city: 'Greeneville' },
      { name: 'Grundy', city: 'Altamont' },
      { name: 'Hamblen', city: 'Morristown' },
      { name: 'Hamilton', city: 'Chattanooga' },
      { name: 'Hancock', city: 'Sneedville' },
      { name: 'Hardeman', city: 'Bolivar' },
      { name: 'Hardin', city: 'Savannah' },
      { name: 'Hawkins', city: 'Rogersville' },
      { name: 'Haywood', city: 'Brownsville' },
      { name: 'Henderson', city: 'Lexington' },
      { name: 'Henry', city: 'Paris' },
      { name: 'Hickman', city: 'Centerville' },
      { name: 'Houston', city: 'Erin' },
      { name: 'Humphreys', city: 'Waverly' },
      { name: 'Jackson', city: 'Gainesboro' },
      { name: 'Jefferson', city: 'Dandridge' },
      { name: 'Johnson', city: 'Mountain City' },
      { name: 'Knox', city: 'Knoxville' },
      { name: 'Lake', city: 'Tiptonville' },
      { name: 'Lauderdale', city: 'Ripley' },
      { name: 'Lawrence', city: 'Lawrenceburg' },
      { name: 'Lewis', city: 'Hohenwald' },
      { name: 'Lincoln', city: 'Fayetteville' },
      { name: 'Loudon', city: 'Loudon' },
      { name: 'Macon', city: 'Lafayette' },
      { name: 'Madison', city: 'Jackson' },
      { name: 'Marion', city: 'Jasper' },
      { name: 'Marshall', city: 'Lewisburg' },
      { name: 'Maury', city: 'Columbia' },
      { name: 'McMinn', city: 'Athens' },
      { name: 'McNairy', city: 'Selmer' },
      { name: 'Meigs', city: 'Decatur' },
      { name: 'Monroe', city: 'Madisonville' },
      { name: 'Montgomery', city: 'Clarksville' },
      { name: 'Moore', city: 'Lynchburg' },
      { name: 'Morgan', city: 'Wartburg' },
      { name: 'Obion', city: 'Union City' },
      { name: 'Overton', city: 'Livingston' },
      { name: 'Perry', city: 'Linden' },
      { name: 'Pickett', city: 'Byrdstown' },
      { name: 'Polk', city: 'Benton' },
      { name: 'Putnam', city: 'Cookeville' },
      { name: 'Rhea', city: 'Dayton' },
      { name: 'Roane', city: 'Kingston' },
      { name: 'Robertson', city: 'Springfield' },
      { name: 'Rutherford', city: 'Murfreesboro' },
      { name: 'Scott', city: 'Huntsville' },
      { name: 'Sequatchie', city: 'Dunlap' },
      { name: 'Sevier', city: 'Sevierville' },
      { name: 'Shelby', city: 'Memphis' },
      { name: 'Smith', city: 'Carthage' },
      { name: 'Stewart', city: 'Dover' },
      { name: 'Sullivan', city: 'Blountville' },
      { name: 'Sumner', city: 'Gallatin' },
      { name: 'Tipton', city: 'Covington' },
      { name: 'Trousdale', city: 'Hartsville' },
      { name: 'Unicoi', city: 'Erwin' },
      { name: 'Union', city: 'Maynardville' },
      { name: 'Van Buren', city: 'Spencer' },
      { name: 'Warren', city: 'McMinnville' },
      { name: 'Washington', city: 'Jonesborough' },
      { name: 'Wayne', city: 'Waynesboro' },
      { name: 'Weakley', city: 'Dresden' },
      { name: 'White', city: 'Sparta' },
      { name: 'Williamson', city: 'Franklin' },
      { name: 'Wilson', city: 'Lebanon' },
    ],
  },
};
