/**
 * Texas State Data
 * 254 counties - largest Hispanic market in the US
 */

import type { StateData } from './types';

export const texasStates: Record<string, StateData> = {
  'texas': {
    slug: 'texas',
    name: 'Texas',
    nameEs: 'Texas',
    countyCount: 254,
    additionalContent: 'Texas tiene la segunda población hispana más grande del país. Los tribunales de familia en los 254 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
  {
    question: '¿Es aceptada en los tribunales de Texas?',
    answer: 'Sí. Nuestro certificado es aceptado en tribunales de los 254 condados de Texas.'
  },
  {
    question: '¿Cuándo recibo mi certificado?',
    answer: 'Inmediatamente. En cuanto complete la clase, puede descargar su certificado. También se lo enviamos por correo electrónico y notificamos a su abogado automáticamente si proporciona su información.'
  },
  {
    question: '¿Tengo que terminar en una sola sesión?',
    answer: 'No. Puede comenzar, pausar y continuar cuando quiera. Su progreso se guarda automáticamente. La mayoría de los padres completan la clase en varios días, ajustándola a sus horarios de trabajo y familia.'
  },
  {
    question: '¿Cuánto tiempo toma la clase?',
    answer: 'La mayoría completa la clase en 4 horas, pero depende de usted. Puede calificar como una clase de 4-6 horas. Usted controla el ritmo — pause, rebobine, tome descansos cuando lo necesite.'
  },
  {
    question: '¿Qué pasa después de pagar?',
    answer: 'Comienza la clase inmediatamente. Avance a su propio ritmo, y su certificado estará listo al instante.'
  },
  {
    question: '¿Cómo le entrego el certificado al tribunal?',
    answer: 'Descargue el PDF e imprímalo, o su abogado puede enviarlo electrónicamente. El certificado incluye un código de verificación seguro y un código QR para que el tribunal pueda confirmar su autenticidad en línea.'
  }
],
    counties: [
      { name: 'Anderson', city: 'Palestine' },
      { name: 'Andrews', city: 'Andrews' },
      { name: 'Angelina', city: 'Lufkin' },
      { name: 'Aransas', city: 'Rockport' },
      { name: 'Archer', city: 'Archer City' },
      { name: 'Armstrong', city: 'Claude' },
      { name: 'Atascosa', city: 'Jourdanton' },
      { name: 'Austin', city: 'Bellville' },
      { name: 'Bailey', city: 'Muleshoe' },
      { name: 'Bandera', city: 'Bandera' },
      { name: 'Bastrop', city: 'Bastrop' },
      { name: 'Baylor', city: 'Seymour' },
      { name: 'Bee', city: 'Beeville' },
      { name: 'Bell', city: 'Belton' },
      { name: 'Bexar', city: 'San Antonio' },
      { name: 'Blanco', city: 'Johnson City' },
      { name: 'Borden', city: 'Gail' },
      { name: 'Bosque', city: 'Meridian' },
      { name: 'Bowie', city: 'Boston' },
      { name: 'Brazoria', city: 'Angleton' },
      { name: 'Brazos', city: 'Bryan' },
      { name: 'Brewster', city: 'Alpine' },
      { name: 'Briscoe', city: 'Silverton' },
      { name: 'Brooks', city: 'Falfurrias' },
      { name: 'Brown', city: 'Brownwood' },
      { name: 'Burleson', city: 'Caldwell' },
      { name: 'Burnet', city: 'Burnet' },
      { name: 'Caldwell', city: 'Lockhart' },
      { name: 'Calhoun', city: 'Port Lavaca' },
      { name: 'Callahan', city: 'Baird' },
      { name: 'Cameron', city: 'Brownsville' },
      { name: 'Camp', city: 'Pittsburg' },
      { name: 'Carson', city: 'Panhandle' },
      { name: 'Cass', city: 'Linden' },
      { name: 'Castro', city: 'Dimmitt' },
      { name: 'Chambers', city: 'Anahuac' },
      { name: 'Cherokee', city: 'Rusk' },
      { name: 'Childress', city: 'Childress' },
      { name: 'Clay', city: 'Henrietta' },
      { name: 'Cochran', city: 'Morton' },
      { name: 'Coke', city: 'Robert Lee' },
      { name: 'Coleman', city: 'Coleman' },
      { name: 'Collin', city: 'McKinney' },
      { name: 'Collingsworth', city: 'Wellington' },
      { name: 'Colorado', city: 'Columbus' },
      { name: 'Comal', city: 'New Braunfels' },
      { name: 'Comanche', city: 'Comanche' },
      { name: 'Concho', city: 'Paint Rock' },
      { name: 'Cooke', city: 'Gainesville' },
      { name: 'Coryell', city: 'Gatesville' },
      { name: 'Cottle', city: 'Paducah' },
      { name: 'Crane', city: 'Crane' },
      { name: 'Crockett', city: 'Ozona' },
      { name: 'Crosby', city: 'Crosbyton' },
      { name: 'Culberson', city: 'Van Horn' },
      { name: 'Dallam', city: 'Dalhart' },
      { name: 'Dallas', city: 'Dallas' },
      { name: 'Dawson', city: 'Lamesa' },
      { name: 'Deaf Smith', city: 'Hereford' },
      { name: 'Delta', city: 'Cooper' },
      { name: 'Denton', city: 'Denton' },
      { name: 'DeWitt', city: 'Cuero' },
      { name: 'Dickens', city: 'Dickens' },
      { name: 'Dimmit', city: 'Carrizo Springs' },
      { name: 'Donley', city: 'Clarendon' },
      { name: 'Duval', city: 'San Diego' },
      { name: 'Eastland', city: 'Eastland' },
      { name: 'Ector', city: 'Odessa' },
      { name: 'Edwards', city: 'Rocksprings' },
      { name: 'Ellis', city: 'Waxahachie' },
      { name: 'El Paso', city: 'El Paso' },
      { name: 'Erath', city: 'Stephenville' },
      { name: 'Falls', city: 'Marlin' },
      { name: 'Fannin', city: 'Bonham' },
      { name: 'Fayette', city: 'La Grange' },
      { name: 'Fisher', city: 'Roby' },
      { name: 'Floyd', city: 'Floydada' },
      { name: 'Foard', city: 'Crowell' },
      { name: 'Fort Bend', city: 'Richmond' },
      { name: 'Franklin', city: 'Mount Vernon' },
      { name: 'Freestone', city: 'Fairfield' },
      { name: 'Frio', city: 'Pearsall' },
      { name: 'Gaines', city: 'Seminole' },
      { name: 'Galveston', city: 'Galveston' },
      { name: 'Garza', city: 'Post' },
      { name: 'Gillespie', city: 'Fredericksburg' },
      { name: 'Glasscock', city: 'Garden City' },
      { name: 'Goliad', city: 'Goliad' },
      { name: 'Gonzales', city: 'Gonzales' },
      { name: 'Gray', city: 'Pampa' },
      { name: 'Grayson', city: 'Sherman' },
      { name: 'Gregg', city: 'Longview' },
      { name: 'Grimes', city: 'Anderson' },
      { name: 'Guadalupe', city: 'Seguin' },
      { name: 'Hale', city: 'Plainview' },
      { name: 'Hall', city: 'Memphis' },
      { name: 'Hamilton', city: 'Hamilton' },
      { name: 'Hansford', city: 'Spearman' },
      { name: 'Hardeman', city: 'Quanah' },
      { name: 'Hardin', city: 'Kountze' },
      { name: 'Harris', city: 'Houston' },
      { name: 'Harrison', city: 'Marshall' },
      { name: 'Hartley', city: 'Channing' },
      { name: 'Haskell', city: 'Haskell' },
      { name: 'Hays', city: 'San Marcos' },
      { name: 'Hemphill', city: 'Canadian' },
      { name: 'Henderson', city: 'Athens' },
      { name: 'Hidalgo', city: 'Edinburg' },
      { name: 'Hill', city: 'Hillsboro' },
      { name: 'Hockley', city: 'Levelland' },
      { name: 'Hood', city: 'Granbury' },
      { name: 'Hopkins', city: 'Sulphur Springs' },
      { name: 'Houston', city: 'Crockett' },
      { name: 'Howard', city: 'Big Spring' },
      { name: 'Hudspeth', city: 'Sierra Blanca' },
      { name: 'Hunt', city: 'Greenville' },
      { name: 'Hutchinson', city: 'Stinnett' },
      { name: 'Irion', city: 'Mertzon' },
      { name: 'Jack', city: 'Jacksboro' },
      { name: 'Jackson', city: 'Edna' },
      { name: 'Jasper', city: 'Jasper' },
      { name: 'Jeff Davis', city: 'Fort Davis' },
      { name: 'Jefferson', city: 'Beaumont' },
      { name: 'Jim Hogg', city: 'Hebbronville' },
      { name: 'Jim Wells', city: 'Alice' },
      { name: 'Johnson', city: 'Cleburne' },
      { name: 'Jones', city: 'Anson' },
      { name: 'Karnes', city: 'Karnes City' },
      { name: 'Kaufman', city: 'Kaufman' },
      { name: 'Kendall', city: 'Boerne' },
      { name: 'Kenedy', city: 'Sarita' },
      { name: 'Kent', city: 'Jayton' },
      { name: 'Kerr', city: 'Kerrville' },
      { name: 'Kimble', city: 'Junction' },
      { name: 'King', city: 'Guthrie' },
      { name: 'Kinney', city: 'Brackettville' },
      { name: 'Kleberg', city: 'Kingsville' },
      { name: 'Knox', city: 'Benjamin' },
      { name: 'Lamar', city: 'Paris' },
      { name: 'Lamb', city: 'Littlefield' },
      { name: 'Lampasas', city: 'Lampasas' },
      { name: 'La Salle', city: 'Cotulla' },
      { name: 'Lavaca', city: 'Hallettsville' },
      { name: 'Lee', city: 'Giddings' },
      { name: 'Leon', city: 'Centerville' },
      { name: 'Liberty', city: 'Liberty' },
      { name: 'Limestone', city: 'Groesbeck' },
      { name: 'Lipscomb', city: 'Lipscomb' },
      { name: 'Live Oak', city: 'George West' },
      { name: 'Llano', city: 'Llano' },
      { name: 'Loving', city: 'Mentone' },
      { name: 'Lubbock', city: 'Lubbock' },
      { name: 'Lynn', city: 'Tahoka' },
      { name: 'McCulloch', city: 'Brady' },
      { name: 'McLennan', city: 'Waco' },
      { name: 'McMullen', city: 'Tilden' },
      { name: 'Madison', city: 'Madisonville' },
      { name: 'Marion', city: 'Jefferson' },
      { name: 'Martin', city: 'Stanton' },
      { name: 'Mason', city: 'Mason' },
      { name: 'Matagorda', city: 'Bay City' },
      { name: 'Maverick', city: 'Eagle Pass' },
      { name: 'Medina', city: 'Hondo' },
      { name: 'Menard', city: 'Menard' },
      { name: 'Midland', city: 'Midland' },
      { name: 'Milam', city: 'Cameron' },
      { name: 'Mills', city: 'Goldthwaite' },
      { name: 'Mitchell', city: 'Colorado City' },
      { name: 'Montague', city: 'Montague' },
      { name: 'Montgomery', city: 'Conroe' },
      { name: 'Moore', city: 'Dumas' },
      { name: 'Morris', city: 'Daingerfield' },
      { name: 'Motley', city: 'Matador' },
      { name: 'Nacogdoches', city: 'Nacogdoches' },
      { name: 'Navarro', city: 'Corsicana' },
      { name: 'Newton', city: 'Newton' },
      { name: 'Nolan', city: 'Sweetwater' },
      { name: 'Nueces', city: 'Corpus Christi' },
      { name: 'Ochiltree', city: 'Perryton' },
      { name: 'Oldham', city: 'Vega' },
      { name: 'Orange', city: 'Orange' },
      { name: 'Palo Pinto', city: 'Palo Pinto' },
      { name: 'Panola', city: 'Carthage' },
      { name: 'Parker', city: 'Weatherford' },
      { name: 'Parmer', city: 'Farwell' },
      { name: 'Pecos', city: 'Fort Stockton' },
      { name: 'Polk', city: 'Livingston' },
      { name: 'Potter', city: 'Amarillo' },
      { name: 'Presidio', city: 'Marfa' },
      { name: 'Rains', city: 'Emory' },
      { name: 'Randall', city: 'Canyon' },
      { name: 'Reagan', city: 'Big Lake' },
      { name: 'Real', city: 'Leakey' },
      { name: 'Red River', city: 'Clarksville' },
      { name: 'Reeves', city: 'Pecos' },
      { name: 'Refugio', city: 'Refugio' },
      { name: 'Roberts', city: 'Miami' },
      { name: 'Robertson', city: 'Franklin' },
      { name: 'Rockwall', city: 'Rockwall' },
      { name: 'Runnels', city: 'Ballinger' },
      { name: 'Rusk', city: 'Henderson' },
      { name: 'Sabine', city: 'Hemphill' },
      { name: 'San Augustine', city: 'San Augustine' },
      { name: 'San Jacinto', city: 'Coldspring' },
      { name: 'San Patricio', city: 'Sinton' },
      { name: 'San Saba', city: 'San Saba' },
      { name: 'Schleicher', city: 'Eldorado' },
      { name: 'Scurry', city: 'Snyder' },
      { name: 'Shackelford', city: 'Albany' },
      { name: 'Shelby', city: 'Center' },
      { name: 'Sherman', city: 'Stratford' },
      { name: 'Smith', city: 'Tyler' },
      { name: 'Somervell', city: 'Glen Rose' },
      { name: 'Starr', city: 'Rio Grande City' },
      { name: 'Stephens', city: 'Breckenridge' },
      { name: 'Sterling', city: 'Sterling City' },
      { name: 'Stonewall', city: 'Aspermont' },
      { name: 'Sutton', city: 'Sonora' },
      { name: 'Swisher', city: 'Tulia' },
      { name: 'Tarrant', city: 'Fort Worth' },
      { name: 'Taylor', city: 'Abilene' },
      { name: 'Terrell', city: 'Sanderson' },
      { name: 'Terry', city: 'Brownfield' },
      { name: 'Throckmorton', city: 'Throckmorton' },
      { name: 'Titus', city: 'Mount Pleasant' },
      { name: 'Tom Green', city: 'San Angelo' },
      { name: 'Travis', city: 'Austin' },
      { name: 'Trinity', city: 'Groveton' },
      { name: 'Tyler', city: 'Woodville' },
      { name: 'Upshur', city: 'Gilmer' },
      { name: 'Upton', city: 'Rankin' },
      { name: 'Uvalde', city: 'Uvalde' },
      { name: 'Val Verde', city: 'Del Rio' },
      { name: 'Van Zandt', city: 'Canton' },
      { name: 'Victoria', city: 'Victoria' },
      { name: 'Walker', city: 'Huntsville' },
      { name: 'Waller', city: 'Hempstead' },
      { name: 'Ward', city: 'Monahans' },
      { name: 'Washington', city: 'Brenham' },
      { name: 'Webb', city: 'Laredo' },
      { name: 'Wharton', city: 'Wharton' },
      { name: 'Wheeler', city: 'Wheeler' },
      { name: 'Wichita', city: 'Wichita Falls' },
      { name: 'Wilbarger', city: 'Vernon' },
      { name: 'Willacy', city: 'Raymondville' },
      { name: 'Williamson', city: 'Georgetown' },
      { name: 'Wilson', city: 'Floresville' },
      { name: 'Winkler', city: 'Kermit' },
      { name: 'Wise', city: 'Decatur' },
      { name: 'Wood', city: 'Quitman' },
      { name: 'Yoakum', city: 'Plains' },
      { name: 'Young', city: 'Graham' },
      { name: 'Zapata', city: 'Zapata' },
      { name: 'Zavala', city: 'Crystal City' },
    ],
  },
};
