/**
 * Texas State Data
 * 254 counties - largest Hispanic market in the US
 * SEO Content Expansion: February 2026 (v5 — polished)
 */

import type { StateData } from './types';

export const texasStates: Record<string, StateData> = {
  'texas': {
    slug: 'texas',
    name: 'Texas',
    nameEs: 'Texas',
    countyCount: 254,
    additionalContent: 'Texas tiene la segunda población hispana más grande del país. Los tribunales de familia en los 254 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',

    // === SEO Content Expansion ===

    metaDescription: 'Clase para padres en Texas — curso online en español para los 254 condados. ¿El juez le ordenó una clase? Empiece hoy, certificado instantáneo. Putting Kids First® — El Original.',

    introContent: `Si el tribunal le dijo que tiene que tomar una clase para padres como parte de su caso de divorcio, custodia, o modificación de una orden judicial, está en el lugar correcto. Nuestra clase para padres en línea es aceptada en los 254 condados de Texas — desde Houston y San Antonio hasta El Paso y el Valle del Río Grande. 100% en español. A su ritmo. Certificado instantáneo al terminar.

El Código de Familia de Texas § 105.009 permite al juez ordenar una clase de educación parental en cualquier caso que involucre hijos menores. Putting Kids First® es el nombre más reconocido en educación parental — líderes desde hace décadas. Miles de padres en Texas ya han presentado nuestro certificado exitosamente. El Original. El Certificado Más Aceptado.`,

    courtContext: 'En Texas, esta clase no es automática en todos los divorcios — el juez decide si la ordena según el mejor interés de los hijos. Pero si su orden judicial dice que debe completar una clase para padres, no hay excepción. Nuestro certificado es aceptado en los 254 condados, ya sea que necesite una clase de coparentalidad o una clase de crianza.',

    faqs: [
      {
        question: '¿Qué clase necesito tomar?',
        answer: `Depende de su situación:

Si su caso es por divorcio, custodia, separación, o modificación de una orden existente → necesita la Clase de Coparentalidad. Es la clase que la gran mayoría de los tribunales en Texas piden.

Si le pidieron una clase de habilidades para padres, o fue referido por un juez, DCFS, un terapeuta, o la escuela de sus hijos → necesita la Clase de Crianza.

Si tiene su orden judicial en inglés y dice "parent education and family stabilization course" o "co-parenting class," necesita la Clase de Coparentalidad. Si dice "parenting skills class," necesita la Clase de Crianza.`
      },
      {
        question: '¿Esta clase para padres es aceptada en los tribunales de Texas?',
        answer: `Sí. Nuestro certificado es aceptado por tribunales en los 254 condados de Texas.

Putting Kids First® es el nombre más reconocido en educación parental — líderes desde hace décadas. El Original. El Certificado Más Aceptado.`
      },
      {
        question: '¿Qué pasa si no completo la clase a tiempo?',
        answer: `El tribunal puede tomar acción seria. En Texas, un juez puede declararlo en desacato, modificar su custodia o tiempo de visitación, e incluso imponer sanciones. Lo más importante: el juez puede emitir una orden final sin esperarlo a usted — y eso puede afectar el resultado de su caso.

No arriesgue su caso. Nuestra clase es de 4 horas y puede completarla desde su teléfono hoy mismo.`
      },
      {
        question: '¿Puedo tomar la clase en español aunque mi caso sea en un tribunal en inglés?',
        answer: `Sí. Nuestra clase es 100% en español, pero su certificado se emite en inglés — que es lo que los tribunales de Texas requieren. En condados fronterizos como El Paso, Webb, y Cameron, muchos empleados del tribunal hablan español, pero los documentos legales deben estar en inglés. Su certificado cumple con ese estándar.`
      },
      {
        question: '¿Lo que digo en la clase puede usarse en mi contra?',
        answer: `No. La ley de Texas protege la confidencialidad de la clase de educación parental. Nada de lo que usted comparta puede ser usado como evidencia en su caso de divorcio o custodia.

Puede completar la clase con tranquilidad, enfocándose en aprender — no en protegerse.`
      },
      {
        question: '¿Cuándo recibo mi certificado y cómo se lo entrego al tribunal?',
        answer: `Su certificado se genera instantáneamente al completar la clase. Es un PDF que puede descargar, imprimir, o enviar por correo electrónico. Cada certificado incluye un código QR y un código de verificación único para que el tribunal confirme su autenticidad en segundos.

En muchos condados de Texas, el certificado debe archivarse con el secretario del tribunal antes de la audiencia final. Lleve una copia impresa al tribunal o entréguelo en la oficina del secretario. Si tiene abogado, envíeselo para que lo incluya en su expediente.`
      },
      {
        question: 'La clase tiene que ser de más de 4 horas. ¿Esta clase califica?',
        answer: `La ley de Texas establece un mínimo de 4 horas y un máximo de 12 horas. Nuestra clase cumple con el requisito mínimo de 4 horas, que es lo que la gran mayoría de los tribunales en Texas aceptan.

Si su orden judicial especifica un número de horas diferente, confirme con el tribunal o con su abogado si tiene uno.`
      },
      {
        question: '¿Ambos padres tienen que tomar la clase?',
        answer: `Revise su orden judicial — en la mayoría de los casos en Texas, ambos padres deben completar la clase por separado. Cada padre se inscribe con su propia cuenta y recibe su propio certificado.

No necesitan coordinar horarios. Cada uno completa la clase a su propio ritmo, en cualquier momento.`
      }
    ],

    counties: [
      { name: 'Anderson', city: 'Palestine' },
      { name: 'Andrews', city: 'Andrews' },
      { name: 'Angelina', city: 'Lufkin' },
      { name: 'Aransas', city: 'Rockport' },
      { name: 'Archer', city: 'Archer City' },
      { name: 'Armstrong', city: 'Claude' },
      { name: 'Atascosa', city: 'Jourdanton' },
      { name: 'Austin', city: 'Bellville' },
      { name: 'Bailey', city: 'Muleshoe' },
      { name: 'Bandera', city: 'Bandera' },
      { name: 'Bastrop', city: 'Bastrop' },
      { name: 'Baylor', city: 'Seymour' },
      { name: 'Bee', city: 'Beeville' },
      { name: 'Bell', city: 'Belton' },
      { name: 'Bexar', city: 'San Antonio' },
      { name: 'Blanco', city: 'Johnson City' },
      { name: 'Borden', city: 'Gail' },
      { name: 'Bosque', city: 'Meridian' },
      { name: 'Bowie', city: 'Boston' },
      { name: 'Brazoria', city: 'Angleton' },
      { name: 'Brazos', city: 'Bryan' },
      { name: 'Brewster', city: 'Alpine' },
      { name: 'Briscoe', city: 'Silverton' },
      { name: 'Brooks', city: 'Falfurrias' },
      { name: 'Brown', city: 'Brownwood' },
      { name: 'Burleson', city: 'Caldwell' },
      { name: 'Burnet', city: 'Burnet' },
      { name: 'Caldwell', city: 'Lockhart' },
      { name: 'Calhoun', city: 'Port Lavaca' },
      { name: 'Callahan', city: 'Baird' },
      { name: 'Cameron', city: 'Brownsville' },
      { name: 'Camp', city: 'Pittsburg' },
      { name: 'Carson', city: 'Panhandle' },
      { name: 'Cass', city: 'Linden' },
      { name: 'Castro', city: 'Dimmitt' },
      { name: 'Chambers', city: 'Anahuac' },
      { name: 'Cherokee', city: 'Rusk' },
      { name: 'Childress', city: 'Childress' },
      { name: 'Clay', city: 'Henrietta' },
      { name: 'Cochran', city: 'Morton' },
      { name: 'Coke', city: 'Robert Lee' },
      { name: 'Coleman', city: 'Coleman' },
      { name: 'Collin', city: 'McKinney' },
      { name: 'Collingsworth', city: 'Wellington' },
      { name: 'Colorado', city: 'Columbus' },
      { name: 'Comal', city: 'New Braunfels' },
      { name: 'Comanche', city: 'Comanche' },
      { name: 'Concho', city: 'Paint Rock' },
      { name: 'Cooke', city: 'Gainesville' },
      { name: 'Coryell', city: 'Gatesville' },
      { name: 'Cottle', city: 'Paducah' },
      { name: 'Crane', city: 'Crane' },
      { name: 'Crockett', city: 'Ozona' },
      { name: 'Crosby', city: 'Crosbyton' },
      { name: 'Culberson', city: 'Van Horn' },
      { name: 'Dallam', city: 'Dalhart' },
      { name: 'Dallas', city: 'Dallas' },
      { name: 'Dawson', city: 'Lamesa' },
      { name: 'Deaf Smith', city: 'Hereford' },
      { name: 'Delta', city: 'Cooper' },
      { name: 'Denton', city: 'Denton' },
      { name: 'DeWitt', city: 'Cuero' },
      { name: 'Dickens', city: 'Dickens' },
      { name: 'Dimmit', city: 'Carrizo Springs' },
      { name: 'Donley', city: 'Clarendon' },
      { name: 'Duval', city: 'San Diego' },
      { name: 'Eastland', city: 'Eastland' },
      { name: 'Ector', city: 'Odessa' },
      { name: 'Edwards', city: 'Rocksprings' },
      { name: 'Ellis', city: 'Waxahachie' },
      { name: 'El Paso', city: 'El Paso' },
      { name: 'Erath', city: 'Stephenville' },
      { name: 'Falls', city: 'Marlin' },
      { name: 'Fannin', city: 'Bonham' },
      { name: 'Fayette', city: 'La Grange' },
      { name: 'Fisher', city: 'Roby' },
      { name: 'Floyd', city: 'Floydada' },
      { name: 'Foard', city: 'Crowell' },
      { name: 'Fort Bend', city: 'Richmond' },
      { name: 'Franklin', city: 'Mount Vernon' },
      { name: 'Freestone', city: 'Fairfield' },
      { name: 'Frio', city: 'Pearsall' },
      { name: 'Gaines', city: 'Seminole' },
      { name: 'Galveston', city: 'Galveston' },
      { name: 'Garza', city: 'Post' },
      { name: 'Gillespie', city: 'Fredericksburg' },
      { name: 'Glasscock', city: 'Garden City' },
      { name: 'Goliad', city: 'Goliad' },
      { name: 'Gonzales', city: 'Gonzales' },
      { name: 'Gray', city: 'Pampa' },
      { name: 'Grayson', city: 'Sherman' },
      { name: 'Gregg', city: 'Longview' },
      { name: 'Grimes', city: 'Anderson' },
      { name: 'Guadalupe', city: 'Seguin' },
      { name: 'Hale', city: 'Plainview' },
      { name: 'Hall', city: 'Memphis' },
      { name: 'Hamilton', city: 'Hamilton' },
      { name: 'Hansford', city: 'Spearman' },
      { name: 'Hardeman', city: 'Quanah' },
      { name: 'Hardin', city: 'Kountze' },
      { name: 'Harris', city: 'Houston' },
      { name: 'Harrison', city: 'Marshall' },
      { name: 'Hartley', city: 'Channing' },
      { name: 'Haskell', city: 'Haskell' },
      { name: 'Hays', city: 'San Marcos' },
      { name: 'Hemphill', city: 'Canadian' },
      { name: 'Henderson', city: 'Athens' },
      { name: 'Hidalgo', city: 'Edinburg' },
      { name: 'Hill', city: 'Hillsboro' },
      { name: 'Hockley', city: 'Levelland' },
      { name: 'Hood', city: 'Granbury' },
      { name: 'Hopkins', city: 'Sulphur Springs' },
      { name: 'Houston', city: 'Crockett' },
      { name: 'Howard', city: 'Big Spring' },
      { name: 'Hudspeth', city: 'Sierra Blanca' },
      { name: 'Hunt', city: 'Greenville' },
      { name: 'Hutchinson', city: 'Stinnett' },
      { name: 'Irion', city: 'Mertzon' },
      { name: 'Jack', city: 'Jacksboro' },
      { name: 'Jackson', city: 'Edna' },
      { name: 'Jasper', city: 'Jasper' },
      { name: 'Jeff Davis', city: 'Fort Davis' },
      { name: 'Jefferson', city: 'Beaumont' },
      { name: 'Jim Hogg', city: 'Hebbronville' },
      { name: 'Jim Wells', city: 'Alice' },
      { name: 'Johnson', city: 'Cleburne' },
      { name: 'Jones', city: 'Anson' },
      { name: 'Karnes', city: 'Karnes City' },
      { name: 'Kaufman', city: 'Kaufman' },
      { name: 'Kendall', city: 'Boerne' },
      { name: 'Kenedy', city: 'Sarita' },
      { name: 'Kent', city: 'Jayton' },
      { name: 'Kerr', city: 'Kerrville' },
      { name: 'Kimble', city: 'Junction' },
      { name: 'King', city: 'Guthrie' },
      { name: 'Kinney', city: 'Brackettville' },
      { name: 'Kleberg', city: 'Kingsville' },
      { name: 'Knox', city: 'Benjamin' },
      { name: 'Lamar', city: 'Paris' },
      { name: 'Lamb', city: 'Littlefield' },
      { name: 'Lampasas', city: 'Lampasas' },
      { name: 'La Salle', city: 'Cotulla' },
      { name: 'Lavaca', city: 'Hallettsville' },
      { name: 'Lee', city: 'Giddings' },
      { name: 'Leon', city: 'Centerville' },
      { name: 'Liberty', city: 'Liberty' },
      { name: 'Limestone', city: 'Groesbeck' },
      { name: 'Lipscomb', city: 'Lipscomb' },
      { name: 'Live Oak', city: 'George West' },
      { name: 'Llano', city: 'Llano' },
      { name: 'Loving', city: 'Mentone' },
      { name: 'Lubbock', city: 'Lubbock' },
      { name: 'Lynn', city: 'Tahoka' },
      { name: 'McCulloch', city: 'Brady' },
      { name: 'McLennan', city: 'Waco' },
      { name: 'McMullen', city: 'Tilden' },
      { name: 'Madison', city: 'Madisonville' },
      { name: 'Marion', city: 'Jefferson' },
      { name: 'Martin', city: 'Stanton' },
      { name: 'Mason', city: 'Mason' },
      { name: 'Matagorda', city: 'Bay City' },
      { name: 'Maverick', city: 'Eagle Pass' },
      { name: 'Medina', city: 'Hondo' },
      { name: 'Menard', city: 'Menard' },
      { name: 'Midland', city: 'Midland' },
      { name: 'Milam', city: 'Cameron' },
      { name: 'Mills', city: 'Goldthwaite' },
      { name: 'Mitchell', city: 'Colorado City' },
      { name: 'Montague', city: 'Montague' },
      { name: 'Montgomery', city: 'Conroe' },
      { name: 'Moore', city: 'Dumas' },
      { name: 'Morris', city: 'Daingerfield' },
      { name: 'Motley', city: 'Matador' },
      { name: 'Nacogdoches', city: 'Nacogdoches' },
      { name: 'Navarro', city: 'Corsicana' },
      { name: 'Newton', city: 'Newton' },
      { name: 'Nolan', city: 'Sweetwater' },
      { name: 'Nueces', city: 'Corpus Christi' },
      { name: 'Ochiltree', city: 'Perryton' },
      { name: 'Oldham', city: 'Vega' },
      { name: 'Orange', city: 'Orange' },
      { name: 'Palo Pinto', city: 'Palo Pinto' },
      { name: 'Panola', city: 'Carthage' },
      { name: 'Parker', city: 'Weatherford' },
      { name: 'Parmer', city: 'Farwell' },
      { name: 'Pecos', city: 'Fort Stockton' },
      { name: 'Polk', city: 'Livingston' },
      { name: 'Potter', city: 'Amarillo' },
      { name: 'Presidio', city: 'Marfa' },
      { name: 'Rains', city: 'Emory' },
      { name: 'Randall', city: 'Canyon' },
      { name: 'Reagan', city: 'Big Lake' },
      { name: 'Real', city: 'Leakey' },
      { name: 'Red River', city: 'Clarksville' },
      { name: 'Reeves', city: 'Pecos' },
      { name: 'Refugio', city: 'Refugio' },
      { name: 'Roberts', city: 'Miami' },
      { name: 'Robertson', city: 'Franklin' },
      { name: 'Rockwall', city: 'Rockwall' },
      { name: 'Runnels', city: 'Ballinger' },
      { name: 'Rusk', city: 'Henderson' },
      { name: 'Sabine', city: 'Hemphill' },
      { name: 'San Augustine', city: 'San Augustine' },
      { name: 'San Jacinto', city: 'Coldspring' },
      { name: 'San Patricio', city: 'Sinton' },
      { name: 'San Saba', city: 'San Saba' },
      { name: 'Schleicher', city: 'Eldorado' },
      { name: 'Scurry', city: 'Snyder' },
      { name: 'Shackelford', city: 'Albany' },
      { name: 'Shelby', city: 'Center' },
      { name: 'Sherman', city: 'Stratford' },
      { name: 'Smith', city: 'Tyler' },
      { name: 'Somervell', city: 'Glen Rose' },
      { name: 'Starr', city: 'Rio Grande City' },
      { name: 'Stephens', city: 'Breckenridge' },
      { name: 'Sterling', city: 'Sterling City' },
      { name: 'Stonewall', city: 'Aspermont' },
      { name: 'Sutton', city: 'Sonora' },
      { name: 'Swisher', city: 'Tulia' },
      { name: 'Tarrant', city: 'Fort Worth' },
      { name: 'Taylor', city: 'Abilene' },
      { name: 'Terrell', city: 'Sanderson' },
      { name: 'Terry', city: 'Brownfield' },
      { name: 'Throckmorton', city: 'Throckmorton' },
      { name: 'Titus', city: 'Mount Pleasant' },
      { name: 'Tom Green', city: 'San Angelo' },
      { name: 'Travis', city: 'Austin' },
      { name: 'Trinity', city: 'Groveton' },
      { name: 'Tyler', city: 'Woodville' },
      { name: 'Upshur', city: 'Gilmer' },
      { name: 'Upton', city: 'Rankin' },
      { name: 'Uvalde', city: 'Uvalde' },
      { name: 'Val Verde', city: 'Del Rio' },
      { name: 'Van Zandt', city: 'Canton' },
      { name: 'Victoria', city: 'Victoria' },
      { name: 'Walker', city: 'Huntsville' },
      { name: 'Waller', city: 'Hempstead' },
      { name: 'Ward', city: 'Monahans' },
      { name: 'Washington', city: 'Brenham' },
      { name: 'Webb', city: 'Laredo' },
      { name: 'Wharton', city: 'Wharton' },
      { name: 'Wheeler', city: 'Wheeler' },
      { name: 'Wichita', city: 'Wichita Falls' },
      { name: 'Wilbarger', city: 'Vernon' },
      { name: 'Willacy', city: 'Raymondville' },
      { name: 'Williamson', city: 'Georgetown' },
      { name: 'Wilson', city: 'Floresville' },
      { name: 'Winkler', city: 'Kermit' },
      { name: 'Wise', city: 'Decatur' },
      { name: 'Wood', city: 'Quitman' },
      { name: 'Yoakum', city: 'Plains' },
      { name: 'Young', city: 'Graham' },
      { name: 'Zapata', city: 'Zapata' },
      { name: 'Zavala', city: 'Crystal City' },
    ],
  },
};
