/**
 * West Mountain Region
 * States: Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, Wyoming
 * 8 states, ~281 counties
 */

import type { StateData } from './types';

export const westMountainStates: Record<string, StateData> = {
  // ===========================================================================
  // ARIZONA
  // ===========================================================================
  'arizona': {
    slug: 'arizona',
    name: 'Arizona',
    nameEs: 'Arizona',
    countyCount: 15,
    additionalContent: 'Arizona tiene una población hispana grande y establecida. Los tribunales de familia en los 15 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Arizona?',
        answer: 'Sí. En los 15 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Apache', city: 'St. Johns' },
      { name: 'Cochise', city: 'Bisbee' },
      { name: 'Coconino', city: 'Flagstaff' },
      { name: 'Gila', city: 'Globe' },
      { name: 'Graham', city: 'Safford' },
      { name: 'Greenlee', city: 'Clifton' },
      { name: 'La Paz', city: 'Parker' },
      { name: 'Maricopa', city: 'Phoenix' },
      { name: 'Mohave', city: 'Kingman' },
      { name: 'Navajo', city: 'Holbrook' },
      { name: 'Pima', city: 'Tucson' },
      { name: 'Pinal', city: 'Florence' },
      { name: 'Santa Cruz', city: 'Nogales' },
      { name: 'Yavapai', city: 'Prescott' },
      { name: 'Yuma', city: 'Yuma' },
    ],
  },

  // ===========================================================================
  // COLORADO
  // ===========================================================================
  'colorado': {
    slug: 'colorado',
    name: 'Colorado',
    nameEs: 'Colorado',
    countyCount: 64,
    additionalContent: 'Colorado tiene una comunidad hispana vibrante y en crecimiento. Los tribunales de familia en los 64 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Colorado?',
        answer: 'Sí. En los 64 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Brighton' },
      { name: 'Alamosa', city: 'Alamosa' },
      { name: 'Arapahoe', city: 'Littleton' },
      { name: 'Archuleta', city: 'Pagosa Springs' },
      { name: 'Baca', city: 'Springfield' },
      { name: 'Bent', city: 'Las Animas' },
      { name: 'Boulder', city: 'Boulder' },
      { name: 'Broomfield', city: 'Broomfield' },
      { name: 'Chaffee', city: 'Salida' },
      { name: 'Cheyenne', city: 'Cheyenne Wells' },
      { name: 'Clear Creek', city: 'Georgetown' },
      { name: 'Conejos', city: 'Conejos' },
      { name: 'Costilla', city: 'San Luis' },
      { name: 'Crowley', city: 'Ordway' },
      { name: 'Custer', city: 'Westcliffe' },
      { name: 'Delta', city: 'Delta' },
      { name: 'Denver', city: 'Denver' },
      { name: 'Dolores', city: 'Dove Creek' },
      { name: 'Douglas', city: 'Castle Rock' },
      { name: 'Eagle', city: 'Eagle' },
      { name: 'Elbert', city: 'Kiowa' },
      { name: 'El Paso', city: 'Colorado Springs' },
      { name: 'Fremont', city: 'Cañon City' },
      { name: 'Garfield', city: 'Glenwood Springs' },
      { name: 'Gilpin', city: 'Central City' },
      { name: 'Grand', city: 'Hot Sulphur Springs' },
      { name: 'Gunnison', city: 'Gunnison' },
      { name: 'Hinsdale', city: 'Lake City' },
      { name: 'Huerfano', city: 'Walsenburg' },
      { name: 'Jackson', city: 'Walden' },
      { name: 'Jefferson', city: 'Golden' },
      { name: 'Kiowa', city: 'Eads' },
      { name: 'Kit Carson', city: 'Burlington' },
      { name: 'Lake', city: 'Leadville' },
      { name: 'La Plata', city: 'Durango' },
      { name: 'Larimer', city: 'Fort Collins' },
      { name: 'Las Animas', city: 'Trinidad' },
      { name: 'Lincoln', city: 'Hugo' },
      { name: 'Logan', city: 'Sterling' },
      { name: 'Mesa', city: 'Grand Junction' },
      { name: 'Mineral', city: 'Creede' },
      { name: 'Moffat', city: 'Craig' },
      { name: 'Montezuma', city: 'Cortez' },
      { name: 'Montrose', city: 'Montrose' },
      { name: 'Morgan', city: 'Fort Morgan' },
      { name: 'Otero', city: 'La Junta' },
      { name: 'Ouray', city: 'Ouray' },
      { name: 'Park', city: 'Fairplay' },
      { name: 'Phillips', city: 'Holyoke' },
      { name: 'Pitkin', city: 'Aspen' },
      { name: 'Prowers', city: 'Lamar' },
      { name: 'Pueblo', city: 'Pueblo' },
      { name: 'Rio Blanco', city: 'Meeker' },
      { name: 'Rio Grande', city: 'Del Norte' },
      { name: 'Routt', city: 'Steamboat Springs' },
      { name: 'Saguache', city: 'Saguache' },
      { name: 'San Juan', city: 'Silverton' },
      { name: 'San Miguel', city: 'Telluride' },
      { name: 'Sedgwick', city: 'Julesburg' },
      { name: 'Summit', city: 'Breckenridge' },
      { name: 'Teller', city: 'Cripple Creek' },
      { name: 'Washington', city: 'Akron' },
      { name: 'Weld', city: 'Greeley' },
      { name: 'Yuma', city: 'Wray' },
    ],
  },

  // ===========================================================================
  // IDAHO
  // ===========================================================================
  'idaho': {
    slug: 'idaho',
    name: 'Idaho',
    nameEs: 'Idaho',
    countyCount: 44,
    additionalContent: 'Idaho tiene una comunidad hispana significativa, especialmente en Boise, Nampa, Caldwell, y las áreas agrícolas del sur del estado. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Idaho?',
        answer: 'Sí. En los 44 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Ada', city: 'Boise' },
      { name: 'Adams', city: 'Council' },
      { name: 'Bannock', city: 'Pocatello' },
      { name: 'Bear Lake', city: 'Paris' },
      { name: 'Benewah', city: 'St. Maries' },
      { name: 'Bingham', city: 'Blackfoot' },
      { name: 'Blaine', city: 'Hailey' },
      { name: 'Boise', city: 'Idaho City' },
      { name: 'Bonner', city: 'Sandpoint' },
      { name: 'Bonneville', city: 'Idaho Falls' },
      { name: 'Boundary', city: 'Bonners Ferry' },
      { name: 'Butte', city: 'Arco' },
      { name: 'Camas', city: 'Fairfield' },
      { name: 'Canyon', city: 'Caldwell' },
      { name: 'Caribou', city: 'Soda Springs' },
      { name: 'Cassia', city: 'Burley' },
      { name: 'Clark', city: 'Dubois' },
      { name: 'Clearwater', city: 'Orofino' },
      { name: 'Custer', city: 'Challis' },
      { name: 'Elmore', city: 'Mountain Home' },
      { name: 'Franklin', city: 'Preston' },
      { name: 'Fremont', city: 'St. Anthony' },
      { name: 'Gem', city: 'Emmett' },
      { name: 'Gooding', city: 'Gooding' },
      { name: 'Idaho', city: 'Grangeville' },
      { name: 'Jefferson', city: 'Rigby' },
      { name: 'Jerome', city: 'Jerome' },
      { name: 'Kootenai', city: "Coeur d'Alene" },
      { name: 'Latah', city: 'Moscow' },
      { name: 'Lemhi', city: 'Salmon' },
      { name: 'Lewis', city: 'Nezperce' },
      { name: 'Lincoln', city: 'Shoshone' },
      { name: 'Madison', city: 'Rexburg' },
      { name: 'Minidoka', city: 'Rupert' },
      { name: 'Nez Perce', city: 'Lewiston' },
      { name: 'Oneida', city: 'Malad City' },
      { name: 'Owyhee', city: 'Murphy' },
      { name: 'Payette', city: 'Payette' },
      { name: 'Power', city: 'American Falls' },
      { name: 'Shoshone', city: 'Wallace' },
      { name: 'Teton', city: 'Driggs' },
      { name: 'Twin Falls', city: 'Twin Falls' },
      { name: 'Valley', city: 'Cascade' },
      { name: 'Washington', city: 'Weiser' },
    ],
  },

  // ===========================================================================
  // MONTANA
  // ===========================================================================
  'montana': {
    slug: 'montana',
    name: 'Montana',
    nameEs: 'Montana',
    countyCount: 56,
    additionalContent: 'Montana tiene una comunidad hispana en crecimiento, especialmente en Billings, Missoula, Great Falls, y las áreas agrícolas del este del estado. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Montana?',
        answer: 'Sí. En los 56 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Beaverhead', city: 'Dillon' },
      { name: 'Big Horn', city: 'Hardin' },
      { name: 'Blaine', city: 'Chinook' },
      { name: 'Broadwater', city: 'Townsend' },
      { name: 'Carbon', city: 'Red Lodge' },
      { name: 'Carter', city: 'Ekalaka' },
      { name: 'Cascade', city: 'Great Falls' },
      { name: 'Chouteau', city: 'Fort Benton' },
      { name: 'Custer', city: 'Miles City' },
      { name: 'Daniels', city: 'Scobey' },
      { name: 'Dawson', city: 'Glendive' },
      { name: 'Deer Lodge', city: 'Anaconda' },
      { name: 'Fallon', city: 'Baker' },
      { name: 'Fergus', city: 'Lewistown' },
      { name: 'Flathead', city: 'Kalispell' },
      { name: 'Gallatin', city: 'Bozeman' },
      { name: 'Garfield', city: 'Jordan' },
      { name: 'Glacier', city: 'Cut Bank' },
      { name: 'Golden Valley', city: 'Ryegate' },
      { name: 'Granite', city: 'Philipsburg' },
      { name: 'Hill', city: 'Havre' },
      { name: 'Jefferson', city: 'Boulder' },
      { name: 'Judith Basin', city: 'Stanford' },
      { name: 'Lake', city: 'Polson' },
      { name: 'Lewis and Clark', city: 'Helena' },
      { name: 'Liberty', city: 'Chester' },
      { name: 'Lincoln', city: 'Libby' },
      { name: 'McCone', city: 'Circle' },
      { name: 'Madison', city: 'Virginia City' },
      { name: 'Meagher', city: 'White Sulphur Springs' },
      { name: 'Mineral', city: 'Superior' },
      { name: 'Missoula', city: 'Missoula' },
      { name: 'Musselshell', city: 'Roundup' },
      { name: 'Park', city: 'Livingston' },
      { name: 'Petroleum', city: 'Winnett' },
      { name: 'Phillips', city: 'Malta' },
      { name: 'Pondera', city: 'Conrad' },
      { name: 'Powder River', city: 'Broadus' },
      { name: 'Powell', city: 'Deer Lodge' },
      { name: 'Prairie', city: 'Terry' },
      { name: 'Ravalli', city: 'Hamilton' },
      { name: 'Richland', city: 'Sidney' },
      { name: 'Roosevelt', city: 'Wolf Point' },
      { name: 'Rosebud', city: 'Forsyth' },
      { name: 'Sanders', city: 'Thompson Falls' },
      { name: 'Sheridan', city: 'Plentywood' },
      { name: 'Silver Bow', city: 'Butte' },
      { name: 'Stillwater', city: 'Columbus' },
      { name: 'Sweet Grass', city: 'Big Timber' },
      { name: 'Teton', city: 'Choteau' },
      { name: 'Toole', city: 'Shelby' },
      { name: 'Treasure', city: 'Hysham' },
      { name: 'Valley', city: 'Glasgow' },
      { name: 'Wheatland', city: 'Harlowton' },
      { name: 'Wibaux', city: 'Wibaux' },
      { name: 'Yellowstone', city: 'Billings' },
    ],
  },

  // ===========================================================================
  // NEVADA
  // ===========================================================================
  'nevada': {
    slug: 'nevada',
    name: 'Nevada',
    nameEs: 'Nevada',
    countyCount: 17,
    additionalContent: 'Nevada tiene una comunidad hispana grande y establecida, especialmente en Las Vegas, Reno, y las áreas rurales del estado. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Nevada?',
        answer: 'Sí. En los 17 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Carson City', city: 'Carson City' },
      { name: 'Churchill', city: 'Fallon' },
      { name: 'Clark', city: 'Las Vegas' },
      { name: 'Douglas', city: 'Minden' },
      { name: 'Elko', city: 'Elko' },
      { name: 'Esmeralda', city: 'Goldfield' },
      { name: 'Eureka', city: 'Eureka' },
      { name: 'Humboldt', city: 'Winnemucca' },
      { name: 'Lander', city: 'Battle Mountain' },
      { name: 'Lincoln', city: 'Pioche' },
      { name: 'Lyon', city: 'Yerington' },
      { name: 'Mineral', city: 'Hawthorne' },
      { name: 'Nye', city: 'Tonopah' },
      { name: 'Pershing', city: 'Lovelock' },
      { name: 'Storey', city: 'Virginia City' },
      { name: 'Washoe', city: 'Reno' },
      { name: 'White Pine', city: 'Ely' },
    ],
  },

  // ===========================================================================
  // NEW MEXICO
  // ===========================================================================
  'new-mexico': {
    slug: 'new-mexico',
    name: 'New Mexico',
    nameEs: 'Nuevo México',
    countyCount: 33,
    additionalContent: 'Nuevo México tiene una comunidad hispana histórica y profundamente arraigada. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Nuevo México?',
        answer: 'Sí. En los 33 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Bernalillo', city: 'Albuquerque' },
      { name: 'Catron', city: 'Reserve' },
      { name: 'Chaves', city: 'Roswell' },
      { name: 'Cibola', city: 'Grants' },
      { name: 'Colfax', city: 'Raton' },
      { name: 'Curry', city: 'Clovis' },
      { name: 'De Baca', city: 'Fort Sumner' },
      { name: 'Doña Ana', city: 'Las Cruces' },
      { name: 'Eddy', city: 'Carlsbad' },
      { name: 'Grant', city: 'Silver City' },
      { name: 'Guadalupe', city: 'Santa Rosa' },
      { name: 'Harding', city: 'Mosquero' },
      { name: 'Hidalgo', city: 'Lordsburg' },
      { name: 'Lea', city: 'Lovington' },
      { name: 'Lincoln', city: 'Carrizozo' },
      { name: 'Los Alamos', city: 'Los Alamos' },
      { name: 'Luna', city: 'Deming' },
      { name: 'McKinley', city: 'Gallup' },
      { name: 'Mora', city: 'Mora' },
      { name: 'Otero', city: 'Alamogordo' },
      { name: 'Quay', city: 'Tucumcari' },
      { name: 'Rio Arriba', city: 'Tierra Amarilla' },
      { name: 'Roosevelt', city: 'Portales' },
      { name: 'Sandoval', city: 'Bernalillo' },
      { name: 'San Juan', city: 'Aztec' },
      { name: 'San Miguel', city: 'Las Vegas' },
      { name: 'Santa Fe', city: 'Santa Fe' },
      { name: 'Sierra', city: 'Truth or Consequences' },
      { name: 'Socorro', city: 'Socorro' },
      { name: 'Taos', city: 'Taos' },
      { name: 'Torrance', city: 'Estancia' },
      { name: 'Union', city: 'Clayton' },
      { name: 'Valencia', city: 'Los Lunas' },
    ],
  },

  // ===========================================================================
  // UTAH
  // ===========================================================================
  'utah': {
    slug: 'utah',
    name: 'Utah',
    nameEs: 'Utah',
    countyCount: 29,
    additionalContent: 'Utah tiene una comunidad hispana en crecimiento, especialmente en Salt Lake City, Ogden, y Provo. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Utah?',
        answer: 'Sí. En los 29 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Beaver', city: 'Beaver' },
      { name: 'Box Elder', city: 'Brigham City' },
      { name: 'Cache', city: 'Logan' },
      { name: 'Carbon', city: 'Price' },
      { name: 'Daggett', city: 'Manila' },
      { name: 'Davis', city: 'Farmington' },
      { name: 'Duchesne', city: 'Duchesne' },
      { name: 'Emery', city: 'Castle Dale' },
      { name: 'Garfield', city: 'Panguitch' },
      { name: 'Grand', city: 'Moab' },
      { name: 'Iron', city: 'Parowan' },
      { name: 'Juab', city: 'Nephi' },
      { name: 'Kane', city: 'Kanab' },
      { name: 'Millard', city: 'Fillmore' },
      { name: 'Morgan', city: 'Morgan' },
      { name: 'Piute', city: 'Junction' },
      { name: 'Rich', city: 'Randolph' },
      { name: 'Salt Lake', city: 'Salt Lake City' },
      { name: 'San Juan', city: 'Monticello' },
      { name: 'Sanpete', city: 'Manti' },
      { name: 'Sevier', city: 'Richfield' },
      { name: 'Summit', city: 'Coalville' },
      { name: 'Tooele', city: 'Tooele' },
      { name: 'Uintah', city: 'Vernal' },
      { name: 'Utah', city: 'Provo' },
      { name: 'Wasatch', city: 'Heber City' },
      { name: 'Washington', city: 'St. George' },
      { name: 'Wayne', city: 'Loa' },
      { name: 'Weber', city: 'Ogden' },
    ],
  },

  // ===========================================================================
  // WYOMING
  // ===========================================================================
  'wyoming': {
    slug: 'wyoming',
    name: 'Wyoming',
    nameEs: 'Wyoming',
    countyCount: 23,
    additionalContent: 'Wyoming tiene una comunidad hispana en crecimiento, especialmente en Cheyenne, Casper, y las áreas de la industria energética. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Wyoming?',
        answer: 'Sí. En los 23 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Albany', city: 'Laramie' },
      { name: 'Big Horn', city: 'Basin' },
      { name: 'Campbell', city: 'Gillette' },
      { name: 'Carbon', city: 'Rawlins' },
      { name: 'Converse', city: 'Douglas' },
      { name: 'Crook', city: 'Sundance' },
      { name: 'Fremont', city: 'Lander' },
      { name: 'Goshen', city: 'Torrington' },
      { name: 'Hot Springs', city: 'Thermopolis' },
      { name: 'Johnson', city: 'Buffalo' },
      { name: 'Laramie', city: 'Cheyenne' },
      { name: 'Lincoln', city: 'Kemmerer' },
      { name: 'Natrona', city: 'Casper' },
      { name: 'Niobrara', city: 'Lusk' },
      { name: 'Park', city: 'Cody' },
      { name: 'Platte', city: 'Wheatland' },
      { name: 'Sheridan', city: 'Sheridan' },
      { name: 'Sublette', city: 'Pinedale' },
      { name: 'Sweetwater', city: 'Green River' },
      { name: 'Teton', city: 'Jackson' },
      { name: 'Uinta', city: 'Evanston' },
      { name: 'Washakie', city: 'Worland' },
      { name: 'Weston', city: 'Newcastle' },
    ],
  },
};
