/**
 * West Pacific Region
 * States: Alaska, California, Hawaii, Oregon, Washington
 * 5 states, ~168 counties
 */

import type { StateData } from './types';

export const westPacificStates: Record<string, StateData> = {
  // ===========================================================================
  // ALASKA
  // ===========================================================================
  'alaska': {
    slug: 'alaska',
    name: 'Alaska',
    nameEs: 'Alaska',
    countyCount: 30,
    additionalContent: 'Alaska tiene una comunidad hispana en crecimiento, especialmente en Anchorage, Fairbanks, y Juneau. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Alaska?',
        answer: 'Sí. En los 30 distritos. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Aleutians East Borough', city: 'Sand Point' },
      { name: 'Aleutians West Census Area', city: 'Unalaska' },
      { name: 'Anchorage Municipality', city: 'Anchorage' },
      { name: 'Bethel Census Area', city: 'Bethel' },
      { name: 'Bristol Bay Borough', city: 'Naknek' },
      { name: 'Chugach Census Area', city: 'Valdez' },
      { name: 'Copper River Census Area', city: 'Glennallen' },
      { name: 'Denali Borough', city: 'Healy' },
      { name: 'Dillingham Census Area', city: 'Dillingham' },
      { name: 'Fairbanks North Star Borough', city: 'Fairbanks' },
      { name: 'Haines Borough', city: 'Haines' },
      { name: 'Hoonah-Angoon Census Area', city: 'Hoonah' },
      { name: 'Juneau City and Borough', city: 'Juneau' },
      { name: 'Kenai Peninsula Borough', city: 'Soldotna' },
      { name: 'Ketchikan Gateway Borough', city: 'Ketchikan' },
      { name: 'Kodiak Island Borough', city: 'Kodiak' },
      { name: 'Kusilvak Census Area', city: 'Hooper Bay' },
      { name: 'Lake and Peninsula Borough', city: 'King Salmon' },
      { name: 'Matanuska-Susitna Borough', city: 'Palmer' },
      { name: 'Nome Census Area', city: 'Nome' },
      { name: 'North Slope Borough', city: 'Utqiagvik' },
      { name: 'Northwest Arctic Borough', city: 'Kotzebue' },
      { name: 'Petersburg Borough', city: 'Petersburg' },
      { name: 'Prince of Wales-Hyder Census Area', city: 'Craig' },
      { name: 'Sitka City and Borough', city: 'Sitka' },
      { name: 'Skagway Municipality', city: 'Skagway' },
      { name: 'Southeast Fairbanks Census Area', city: 'Delta Junction' },
      { name: 'Wrangell City and Borough', city: 'Wrangell' },
      { name: 'Yakutat City and Borough', city: 'Yakutat' },
      { name: 'Yukon-Koyukuk Census Area', city: 'Galena' },
    ],
  },

  // ===========================================================================
  // CALIFORNIA
  // ===========================================================================
  'california': {
    slug: 'california',
    name: 'California',
    nameEs: 'California',
    countyCount: 58,
    additionalContent: 'California tiene la población hispana más grande del país. Los tribunales de familia en los 58 condados reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de California?',
        answer: 'Sí. En los 58 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Alameda', city: 'Oakland' },
      { name: 'Alpine', city: 'Markleeville' },
      { name: 'Amador', city: 'Jackson' },
      { name: 'Butte', city: 'Oroville' },
      { name: 'Calaveras', city: 'San Andreas' },
      { name: 'Colusa', city: 'Colusa' },
      { name: 'Contra Costa', city: 'Martinez' },
      { name: 'Del Norte', city: 'Crescent City' },
      { name: 'El Dorado', city: 'Placerville' },
      { name: 'Fresno', city: 'Fresno' },
      { name: 'Glenn', city: 'Willows' },
      { name: 'Humboldt', city: 'Eureka' },
      { name: 'Imperial', city: 'El Centro' },
      { name: 'Inyo', city: 'Independence' },
      { name: 'Kern', city: 'Bakersfield' },
      { name: 'Kings', city: 'Hanford' },
      { name: 'Lake', city: 'Lakeport' },
      { name: 'Lassen', city: 'Susanville' },
      { name: 'Los Angeles', city: 'Los Angeles' },
      { name: 'Madera', city: 'Madera' },
      { name: 'Marin', city: 'San Rafael' },
      { name: 'Mariposa', city: 'Mariposa' },
      { name: 'Mendocino', city: 'Ukiah' },
      { name: 'Merced', city: 'Merced' },
      { name: 'Modoc', city: 'Alturas' },
      { name: 'Mono', city: 'Bridgeport' },
      { name: 'Monterey', city: 'Salinas' },
      { name: 'Napa', city: 'Napa' },
      { name: 'Nevada', city: 'Nevada City' },
      { name: 'Orange', city: 'Santa Ana' },
      { name: 'Placer', city: 'Auburn' },
      { name: 'Plumas', city: 'Quincy' },
      { name: 'Riverside', city: 'Riverside' },
      { name: 'Sacramento', city: 'Sacramento' },
      { name: 'San Benito', city: 'Hollister' },
      { name: 'San Bernardino', city: 'San Bernardino' },
      { name: 'San Diego', city: 'San Diego' },
      { name: 'San Francisco', city: 'San Francisco' },
      { name: 'San Joaquin', city: 'Stockton' },
      { name: 'San Luis Obispo', city: 'San Luis Obispo' },
      { name: 'San Mateo', city: 'Redwood City' },
      { name: 'Santa Barbara', city: 'Santa Barbara' },
      { name: 'Santa Clara', city: 'San Jose' },
      { name: 'Santa Cruz', city: 'Santa Cruz' },
      { name: 'Shasta', city: 'Redding' },
      { name: 'Sierra', city: 'Downieville' },
      { name: 'Siskiyou', city: 'Yreka' },
      { name: 'Solano', city: 'Fairfield' },
      { name: 'Sonoma', city: 'Santa Rosa' },
      { name: 'Stanislaus', city: 'Modesto' },
      { name: 'Sutter', city: 'Yuba City' },
      { name: 'Tehama', city: 'Red Bluff' },
      { name: 'Trinity', city: 'Weaverville' },
      { name: 'Tulare', city: 'Visalia' },
      { name: 'Tuolumne', city: 'Sonora' },
      { name: 'Ventura', city: 'Ventura' },
      { name: 'Yolo', city: 'Woodland' },
      { name: 'Yuba', city: 'Marysville' },
    ],
  },

  // ===========================================================================
  // HAWAII
  // ===========================================================================
  'hawaii': {
    slug: 'hawaii',
    name: 'Hawaii',
    nameEs: 'Hawái',
    countyCount: 5,
    additionalContent: 'Hawái tiene una comunidad hispana diversa, especialmente en Honolulu y las bases militares. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Hawái?',
        answer: 'Sí. En los 5 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Hawaii County', city: 'Hilo' },
      { name: 'Honolulu County', city: 'Honolulu' },
      { name: 'Kalawao County', city: 'Kalaupapa' },
      { name: 'Kauai County', city: 'Lihue' },
      { name: 'Maui County', city: 'Wailuku' },
    ],
  },

  // ===========================================================================
  // OREGON
  // ===========================================================================
  'oregon': {
    slug: 'oregon',
    name: 'Oregon',
    nameEs: 'Oregón',
    countyCount: 36,
    additionalContent: 'Oregón tiene una comunidad hispana significativa, especialmente en Portland, Salem, y el valle de Willamette. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Oregón?',
        answer: 'Sí. En los 36 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Baker', city: 'Baker City' },
      { name: 'Benton', city: 'Corvallis' },
      { name: 'Clackamas', city: 'Oregon City' },
      { name: 'Clatsop', city: 'Astoria' },
      { name: 'Columbia', city: 'St. Helens' },
      { name: 'Coos', city: 'Coquille' },
      { name: 'Crook', city: 'Prineville' },
      { name: 'Curry', city: 'Gold Beach' },
      { name: 'Deschutes', city: 'Bend' },
      { name: 'Douglas', city: 'Roseburg' },
      { name: 'Gilliam', city: 'Condon' },
      { name: 'Grant', city: 'Canyon City' },
      { name: 'Harney', city: 'Burns' },
      { name: 'Hood River', city: 'Hood River' },
      { name: 'Jackson', city: 'Medford' },
      { name: 'Jefferson', city: 'Madras' },
      { name: 'Josephine', city: 'Grants Pass' },
      { name: 'Klamath', city: 'Klamath Falls' },
      { name: 'Lake', city: 'Lakeview' },
      { name: 'Lane', city: 'Eugene' },
      { name: 'Lincoln', city: 'Newport' },
      { name: 'Linn', city: 'Albany' },
      { name: 'Malheur', city: 'Vale' },
      { name: 'Marion', city: 'Salem' },
      { name: 'Morrow', city: 'Heppner' },
      { name: 'Multnomah', city: 'Portland' },
      { name: 'Polk', city: 'Dallas' },
      { name: 'Sherman', city: 'Moro' },
      { name: 'Tillamook', city: 'Tillamook' },
      { name: 'Umatilla', city: 'Pendleton' },
      { name: 'Union', city: 'La Grande' },
      { name: 'Wallowa', city: 'Enterprise' },
      { name: 'Wasco', city: 'The Dalles' },
      { name: 'Washington', city: 'Hillsboro' },
      { name: 'Wheeler', city: 'Fossil' },
      { name: 'Yamhill', city: 'McMinnville' },
    ],
  },

  // ===========================================================================
  // WASHINGTON
  // ===========================================================================
  'washington': {
    slug: 'washington',
    name: 'Washington',
    nameEs: 'Washington',
    countyCount: 39,
    additionalContent: 'Washington tiene una comunidad hispana grande y diversa, especialmente en Seattle, Yakima, Tri-Cities, y las áreas agrícolas del centro del estado. Los tribunales de familia en todo el estado reconocen nuestro nombre y aceptan nuestros certificados. El Original.',
    faqs: [
      {
        question: '¿Es aceptada en los tribunales de Washington?',
        answer: 'Sí. En los 39 condados. El Original. El Certificado Más Aceptado.',
      },
      {
        question: '¿Cuándo recibo mi certificado?',
        answer: 'Inmediatamente. Notificamos a su abogado automáticamente.',
      },
      {
        question: '¿Cuánto tiempo toma?',
        answer: '4 horas. A su ritmo.',
      },
      {
        question: '¿Puedo tomarla en mi teléfono?',
        answer: 'Sí. Teléfono, tableta o computadora.',
      },
    ],
    counties: [
      { name: 'Adams', city: 'Ritzville' },
      { name: 'Asotin', city: 'Asotin' },
      { name: 'Benton', city: 'Prosser' },
      { name: 'Chelan', city: 'Wenatchee' },
      { name: 'Clallam', city: 'Port Angeles' },
      { name: 'Clark', city: 'Vancouver' },
      { name: 'Columbia', city: 'Dayton' },
      { name: 'Cowlitz', city: 'Kelso' },
      { name: 'Douglas', city: 'Waterville' },
      { name: 'Ferry', city: 'Republic' },
      { name: 'Franklin', city: 'Pasco' },
      { name: 'Garfield', city: 'Pomeroy' },
      { name: 'Grant', city: 'Ephrata' },
      { name: 'Grays Harbor', city: 'Montesano' },
      { name: 'Island', city: 'Coupeville' },
      { name: 'Jefferson', city: 'Port Townsend' },
      { name: 'King', city: 'Seattle' },
      { name: 'Kitsap', city: 'Port Orchard' },
      { name: 'Kittitas', city: 'Ellensburg' },
      { name: 'Klickitat', city: 'Goldendale' },
      { name: 'Lewis', city: 'Chehalis' },
      { name: 'Lincoln', city: 'Davenport' },
      { name: 'Mason', city: 'Shelton' },
      { name: 'Okanogan', city: 'Okanogan' },
      { name: 'Pacific', city: 'South Bend' },
      { name: 'Pend Oreille', city: 'Newport' },
      { name: 'Pierce', city: 'Tacoma' },
      { name: 'San Juan', city: 'Friday Harbor' },
      { name: 'Skagit', city: 'Mount Vernon' },
      { name: 'Skamania', city: 'Stevenson' },
      { name: 'Snohomish', city: 'Everett' },
      { name: 'Spokane', city: 'Spokane' },
      { name: 'Stevens', city: 'Colville' },
      { name: 'Thurston', city: 'Olympia' },
      { name: 'Wahkiakum', city: 'Cathlamet' },
      { name: 'Walla Walla', city: 'Walla Walla' },
      { name: 'Whatcom', city: 'Bellingham' },
      { name: 'Whitman', city: 'Colfax' },
      { name: 'Yakima', city: 'Yakima' },
    ],
  },
};
